// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: materialization.proto

package materializationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerVerification int32

const (
	ContainerVerification_CONTAINER_VERIFICATION_UNSPECIFIED ContainerVerification = 0
	// Only the pinned reference and declared platform were validated. No registry
	// lookup, pull, dependency inspection, or hermetic build was performed.
	ContainerVerification_PINNED_REFERENCE_ONLY ContainerVerification = 1
)

// Enum value maps for ContainerVerification.
var (
	ContainerVerification_name = map[int32]string{
		0: "CONTAINER_VERIFICATION_UNSPECIFIED",
		1: "PINNED_REFERENCE_ONLY",
	}
	ContainerVerification_value = map[string]int32{
		"CONTAINER_VERIFICATION_UNSPECIFIED": 0,
		"PINNED_REFERENCE_ONLY":              1,
	}
)

func (x ContainerVerification) Enum() *ContainerVerification {
	p := new(ContainerVerification)
	*p = x
	return p
}

func (x ContainerVerification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerVerification) Descriptor() protoreflect.EnumDescriptor {
	return file_materialization_proto_enumTypes[0].Descriptor()
}

func (ContainerVerification) Type() protoreflect.EnumType {
	return &file_materialization_proto_enumTypes[0]
}

func (x ContainerVerification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerVerification.Descriptor instead.
func (ContainerVerification) EnumDescriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{0}
}

type PythonVerification int32

const (
	PythonVerification_PYTHON_VERIFICATION_UNSPECIFIED PythonVerification = 0
	// Every locked runtime package (no dev groups or extras) is installed at its
	// version from a current uv.lock; other installed packages are permitted.
	PythonVerification_LOCK_SYNC_CHECKED PythonVerification = 1
	// Only requires-python and applicable direct requirements were checked.
	PythonVerification_DIRECT_REQUIREMENTS_SATISFIED PythonVerification = 2
	// No [project] metadata was declared, so no requirement was checked.
	PythonVerification_UNDECLARED PythonVerification = 3
)

// Enum value maps for PythonVerification.
var (
	PythonVerification_name = map[int32]string{
		0: "PYTHON_VERIFICATION_UNSPECIFIED",
		1: "LOCK_SYNC_CHECKED",
		2: "DIRECT_REQUIREMENTS_SATISFIED",
		3: "UNDECLARED",
	}
	PythonVerification_value = map[string]int32{
		"PYTHON_VERIFICATION_UNSPECIFIED": 0,
		"LOCK_SYNC_CHECKED":               1,
		"DIRECT_REQUIREMENTS_SATISFIED":   2,
		"UNDECLARED":                      3,
	}
)

func (x PythonVerification) Enum() *PythonVerification {
	p := new(PythonVerification)
	*p = x
	return p
}

func (x PythonVerification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PythonVerification) Descriptor() protoreflect.EnumDescriptor {
	return file_materialization_proto_enumTypes[1].Descriptor()
}

func (PythonVerification) Type() protoreflect.EnumType {
	return &file_materialization_proto_enumTypes[1]
}

func (x PythonVerification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PythonVerification.Descriptor instead.
func (PythonVerification) EnumDescriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{1}
}

// Portable inputs, independent of a checkout, compiler process, and target.
// Environment refs refer to requirement identities in the compiled plan, not
// frontend aliases. Source package identity and archive byte identity differ.
// Hashes use canonical-json-v0, excluding only the root self-hash field.
type MaterializationSpec struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	SchemaVersion  *uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3,oneof" json:"schema_version,omitempty"`
	SpecHash       *string                 `protobuf:"bytes,2,opt,name=spec_hash,json=specHash,proto3,oneof" json:"spec_hash,omitempty"`
	Environments   []*EnvironmentSelection `protobuf:"bytes,3,rep,name=environments,proto3" json:"environments,omitempty"`
	SourceArchives []*SourceArchive        `protobuf:"bytes,4,rep,name=source_archives,json=sourceArchives,proto3" json:"source_archives,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MaterializationSpec) Reset() {
	*x = MaterializationSpec{}
	mi := &file_materialization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializationSpec) ProtoMessage() {}

func (x *MaterializationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_materialization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializationSpec.ProtoReflect.Descriptor instead.
func (*MaterializationSpec) Descriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{0}
}

func (x *MaterializationSpec) GetSchemaVersion() uint32 {
	if x != nil && x.SchemaVersion != nil {
		return *x.SchemaVersion
	}
	return 0
}

func (x *MaterializationSpec) GetSpecHash() string {
	if x != nil && x.SpecHash != nil {
		return *x.SpecHash
	}
	return ""
}

func (x *MaterializationSpec) GetEnvironments() []*EnvironmentSelection {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *MaterializationSpec) GetSourceArchives() []*SourceArchive {
	if x != nil {
		return x.SourceArchives
	}
	return nil
}

type EnvironmentSelection struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentRef    *string                `protobuf:"bytes,1,opt,name=environment_ref,json=environmentRef,proto3,oneof" json:"environment_ref,omitempty"`
	ExistingContainer *ExistingContainer     `protobuf:"bytes,2,opt,name=existing_container,json=existingContainer,proto3,oneof" json:"existing_container,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnvironmentSelection) Reset() {
	*x = EnvironmentSelection{}
	mi := &file_materialization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentSelection) ProtoMessage() {}

func (x *EnvironmentSelection) ProtoReflect() protoreflect.Message {
	mi := &file_materialization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentSelection.ProtoReflect.Descriptor instead.
func (*EnvironmentSelection) Descriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentSelection) GetEnvironmentRef() string {
	if x != nil && x.EnvironmentRef != nil {
		return *x.EnvironmentRef
	}
	return ""
}

func (x *EnvironmentSelection) GetExistingContainer() *ExistingContainer {
	if x != nil {
		return x.ExistingContainer
	}
	return nil
}

// An externally supplied immutable image, not a build recipe. Command and
// working directory remain execution requirements in the plan.
type ExistingContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *string                `protobuf:"bytes,1,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Platform      *string                `protobuf:"bytes,2,opt,name=platform,proto3,oneof" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistingContainer) Reset() {
	*x = ExistingContainer{}
	mi := &file_materialization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistingContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistingContainer) ProtoMessage() {}

func (x *ExistingContainer) ProtoReflect() protoreflect.Message {
	mi := &file_materialization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistingContainer.ProtoReflect.Descriptor instead.
func (*ExistingContainer) Descriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{2}
}

func (x *ExistingContainer) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *ExistingContainer) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

type SourceArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageHash   *string                `protobuf:"bytes,1,opt,name=package_hash,json=packageHash,proto3,oneof" json:"package_hash,omitempty"`
	ArchiveHash   *string                `protobuf:"bytes,2,opt,name=archive_hash,json=archiveHash,proto3,oneof" json:"archive_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceArchive) Reset() {
	*x = SourceArchive{}
	mi := &file_materialization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceArchive) ProtoMessage() {}

func (x *SourceArchive) ProtoReflect() protoreflect.Message {
	mi := &file_materialization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceArchive.ProtoReflect.Descriptor instead.
func (*SourceArchive) Descriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{3}
}

func (x *SourceArchive) GetPackageHash() string {
	if x != nil && x.PackageHash != nil {
		return *x.PackageHash
	}
	return ""
}

func (x *SourceArchive) GetArchiveHash() string {
	if x != nil && x.ArchiveHash != nil {
		return *x.ArchiveHash
	}
	return ""
}

type MaterializationManifest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	SchemaVersion *uint32                   `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3,oneof" json:"schema_version,omitempty"`
	ManifestHash  *string                   `protobuf:"bytes,2,opt,name=manifest_hash,json=manifestHash,proto3,oneof" json:"manifest_hash,omitempty"`
	SpecHash      *string                   `protobuf:"bytes,3,opt,name=spec_hash,json=specHash,proto3,oneof" json:"spec_hash,omitempty"`
	Environments  []*EnvironmentRealization `protobuf:"bytes,4,rep,name=environments,proto3" json:"environments,omitempty"`
	// Both semantic package identity and exact archive bytes have been checked.
	SourceArchives      []*SourceArchive `protobuf:"bytes,5,rep,name=source_archives,json=sourceArchives,proto3" json:"source_archives,omitempty"`
	MaterializerName    *string          `protobuf:"bytes,6,opt,name=materializer_name,json=materializerName,proto3,oneof" json:"materializer_name,omitempty"`
	MaterializerVersion *string          `protobuf:"bytes,7,opt,name=materializer_version,json=materializerVersion,proto3,oneof" json:"materializer_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MaterializationManifest) Reset() {
	*x = MaterializationManifest{}
	mi := &file_materialization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializationManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializationManifest) ProtoMessage() {}

func (x *MaterializationManifest) ProtoReflect() protoreflect.Message {
	mi := &file_materialization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializationManifest.ProtoReflect.Descriptor instead.
func (*MaterializationManifest) Descriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{4}
}

func (x *MaterializationManifest) GetSchemaVersion() uint32 {
	if x != nil && x.SchemaVersion != nil {
		return *x.SchemaVersion
	}
	return 0
}

func (x *MaterializationManifest) GetManifestHash() string {
	if x != nil && x.ManifestHash != nil {
		return *x.ManifestHash
	}
	return ""
}

func (x *MaterializationManifest) GetSpecHash() string {
	if x != nil && x.SpecHash != nil {
		return *x.SpecHash
	}
	return ""
}

func (x *MaterializationManifest) GetEnvironments() []*EnvironmentRealization {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *MaterializationManifest) GetSourceArchives() []*SourceArchive {
	if x != nil {
		return x.SourceArchives
	}
	return nil
}

func (x *MaterializationManifest) GetMaterializerName() string {
	if x != nil && x.MaterializerName != nil {
		return *x.MaterializerName
	}
	return ""
}

func (x *MaterializationManifest) GetMaterializerVersion() string {
	if x != nil && x.MaterializerVersion != nil {
		return *x.MaterializerVersion
	}
	return ""
}

type EnvironmentRealization struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentRef *string                `protobuf:"bytes,1,opt,name=environment_ref,json=environmentRef,proto3,oneof" json:"environment_ref,omitempty"`
	// Excludes environment_ref and source/workflow/deployment identities so an
	// identical image/platform selection can be shared across workflows.
	RealizationHash   *string                `protobuf:"bytes,2,opt,name=realization_hash,json=realizationHash,proto3,oneof" json:"realization_hash,omitempty"`
	ExistingContainer *ExistingContainer     `protobuf:"bytes,3,opt,name=existing_container,json=existingContainer,proto3,oneof" json:"existing_container,omitempty"`
	Verification      *ContainerVerification `protobuf:"varint,4,opt,name=verification,proto3,enum=massive.materialization.v0.ContainerVerification,oneof" json:"verification,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnvironmentRealization) Reset() {
	*x = EnvironmentRealization{}
	mi := &file_materialization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentRealization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentRealization) ProtoMessage() {}

func (x *EnvironmentRealization) ProtoReflect() protoreflect.Message {
	mi := &file_materialization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentRealization.ProtoReflect.Descriptor instead.
func (*EnvironmentRealization) Descriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{5}
}

func (x *EnvironmentRealization) GetEnvironmentRef() string {
	if x != nil && x.EnvironmentRef != nil {
		return *x.EnvironmentRef
	}
	return ""
}

func (x *EnvironmentRealization) GetRealizationHash() string {
	if x != nil && x.RealizationHash != nil {
		return *x.RealizationHash
	}
	return ""
}

func (x *EnvironmentRealization) GetExistingContainer() *ExistingContainer {
	if x != nil {
		return x.ExistingContainer
	}
	return nil
}

func (x *EnvironmentRealization) GetVerification() ContainerVerification {
	if x != nil && x.Verification != nil {
		return *x.Verification
	}
	return ContainerVerification_CONTAINER_VERIFICATION_UNSPECIFIED
}

// RealizedEnvironment records an existing Python environment that passed
// dependency preflight. It is stored content-addressed as canonical protobuf
// JSON and referenced from the run journal. Interpreter paths, installer
// records, and RECORD file hashes are excluded: they differ between equivalent
// environments (console-script shebangs embed paths).
type RealizedEnvironment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion *uint32                `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3,oneof" json:"schema_version,omitempty"`
	// canonical-json-v0 of recipe "python-requirement" v1; see hashing.md.
	RequirementHash *string `protobuf:"bytes,2,opt,name=requirement_hash,json=requirementHash,proto3,oneof" json:"requirement_hash,omitempty"`
	// canonical-json-v0 of recipe "existing-python" v1; see hashing.md.
	RealizationHash *string                    `protobuf:"bytes,3,opt,name=realization_hash,json=realizationHash,proto3,oneof" json:"realization_hash,omitempty"`
	Requirement     *PythonRequirement         `protobuf:"bytes,4,opt,name=requirement,proto3,oneof" json:"requirement,omitempty"`
	Realization     *ExistingPythonRealization `protobuf:"bytes,5,opt,name=realization,proto3,oneof" json:"realization,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RealizedEnvironment) Reset() {
	*x = RealizedEnvironment{}
	mi := &file_materialization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealizedEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealizedEnvironment) ProtoMessage() {}

func (x *RealizedEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_materialization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealizedEnvironment.ProtoReflect.Descriptor instead.
func (*RealizedEnvironment) Descriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{6}
}

func (x *RealizedEnvironment) GetSchemaVersion() uint32 {
	if x != nil && x.SchemaVersion != nil {
		return *x.SchemaVersion
	}
	return 0
}

func (x *RealizedEnvironment) GetRequirementHash() string {
	if x != nil && x.RequirementHash != nil {
		return *x.RequirementHash
	}
	return ""
}

func (x *RealizedEnvironment) GetRealizationHash() string {
	if x != nil && x.RealizationHash != nil {
		return *x.RealizationHash
	}
	return ""
}

func (x *RealizedEnvironment) GetRequirement() *PythonRequirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *RealizedEnvironment) GetRealization() *ExistingPythonRealization {
	if x != nil {
		return x.Realization
	}
	return nil
}

// Dependency inputs only. [tool.massive.source] is source identity, not here.
type PythonRequirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absent when pyproject.toml declares no requires-python.
	RequiresPython *string `protobuf:"bytes,1,opt,name=requires_python,json=requiresPython,proto3,oneof" json:"requires_python,omitempty"`
	// SHA-256 of the exact uv.lock bytes. When present, the lock defines the
	// dependency set and `dependencies` is empty.
	LockHash *string `protobuf:"bytes,2,opt,name=lock_hash,json=lockHash,proto3,oneof" json:"lock_hash,omitempty"`
	// [project].dependencies with canonical names, sorted; only without a lock.
	Dependencies  []string `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythonRequirement) Reset() {
	*x = PythonRequirement{}
	mi := &file_materialization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythonRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythonRequirement) ProtoMessage() {}

func (x *PythonRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_materialization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythonRequirement.ProtoReflect.Descriptor instead.
func (*PythonRequirement) Descriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{7}
}

func (x *PythonRequirement) GetRequiresPython() string {
	if x != nil && x.RequiresPython != nil {
		return *x.RequiresPython
	}
	return ""
}

func (x *PythonRequirement) GetLockHash() string {
	if x != nil && x.LockHash != nil {
		return *x.LockHash
	}
	return ""
}

func (x *PythonRequirement) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type ExistingPythonRealization struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Implementation *string                `protobuf:"bytes,1,opt,name=implementation,proto3,oneof" json:"implementation,omitempty"`
	PythonVersion  *string                `protobuf:"bytes,2,opt,name=python_version,json=pythonVersion,proto3,oneof" json:"python_version,omitempty"`
	CacheTag       *string                `protobuf:"bytes,3,opt,name=cache_tag,json=cacheTag,proto3,oneof" json:"cache_tag,omitempty"`
	// sysconfig.get_platform(), such as linux-x86_64 or macosx-14.0-arm64.
	SysconfigPlatform *string `protobuf:"bytes,4,opt,name=sysconfig_platform,json=sysconfigPlatform,proto3,oneof" json:"sysconfig_platform,omitempty"`
	Os                *string `protobuf:"bytes,5,opt,name=os,proto3,oneof" json:"os,omitempty"`
	Arch              *string `protobuf:"bytes,6,opt,name=arch,proto3,oneof" json:"arch,omitempty"`
	// Sorted by canonical name; the first copy on sys.path.
	Distributions       []*InstalledDistribution `protobuf:"bytes,7,rep,name=distributions,proto3" json:"distributions,omitempty"`
	MaterializerName    *string                  `protobuf:"bytes,8,opt,name=materializer_name,json=materializerName,proto3,oneof" json:"materializer_name,omitempty"`
	MaterializerVersion *string                  `protobuf:"bytes,9,opt,name=materializer_version,json=materializerVersion,proto3,oneof" json:"materializer_version,omitempty"`
	Verification        *PythonVerification      `protobuf:"varint,10,opt,name=verification,proto3,enum=massive.materialization.v0.PythonVerification,oneof" json:"verification,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExistingPythonRealization) Reset() {
	*x = ExistingPythonRealization{}
	mi := &file_materialization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistingPythonRealization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistingPythonRealization) ProtoMessage() {}

func (x *ExistingPythonRealization) ProtoReflect() protoreflect.Message {
	mi := &file_materialization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistingPythonRealization.ProtoReflect.Descriptor instead.
func (*ExistingPythonRealization) Descriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{8}
}

func (x *ExistingPythonRealization) GetImplementation() string {
	if x != nil && x.Implementation != nil {
		return *x.Implementation
	}
	return ""
}

func (x *ExistingPythonRealization) GetPythonVersion() string {
	if x != nil && x.PythonVersion != nil {
		return *x.PythonVersion
	}
	return ""
}

func (x *ExistingPythonRealization) GetCacheTag() string {
	if x != nil && x.CacheTag != nil {
		return *x.CacheTag
	}
	return ""
}

func (x *ExistingPythonRealization) GetSysconfigPlatform() string {
	if x != nil && x.SysconfigPlatform != nil {
		return *x.SysconfigPlatform
	}
	return ""
}

func (x *ExistingPythonRealization) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

func (x *ExistingPythonRealization) GetArch() string {
	if x != nil && x.Arch != nil {
		return *x.Arch
	}
	return ""
}

func (x *ExistingPythonRealization) GetDistributions() []*InstalledDistribution {
	if x != nil {
		return x.Distributions
	}
	return nil
}

func (x *ExistingPythonRealization) GetMaterializerName() string {
	if x != nil && x.MaterializerName != nil {
		return *x.MaterializerName
	}
	return ""
}

func (x *ExistingPythonRealization) GetMaterializerVersion() string {
	if x != nil && x.MaterializerVersion != nil {
		return *x.MaterializerVersion
	}
	return ""
}

func (x *ExistingPythonRealization) GetVerification() PythonVerification {
	if x != nil && x.Verification != nil {
		return *x.Verification
	}
	return PythonVerification_PYTHON_VERIFICATION_UNSPECIFIED
}

type InstalledDistribution struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Version *string                `protobuf:"bytes,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// PEP 610 direct_url.json is present (a path, URL, or VCS install).
	Direct        *bool `protobuf:"varint,3,opt,name=direct,proto3,oneof" json:"direct,omitempty"`
	Editable      *bool `protobuf:"varint,4,opt,name=editable,proto3,oneof" json:"editable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledDistribution) Reset() {
	*x = InstalledDistribution{}
	mi := &file_materialization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledDistribution) ProtoMessage() {}

func (x *InstalledDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_materialization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledDistribution.ProtoReflect.Descriptor instead.
func (*InstalledDistribution) Descriptor() ([]byte, []int) {
	return file_materialization_proto_rawDescGZIP(), []int{9}
}

func (x *InstalledDistribution) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *InstalledDistribution) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *InstalledDistribution) GetDirect() bool {
	if x != nil && x.Direct != nil {
		return *x.Direct
	}
	return false
}

func (x *InstalledDistribution) GetEditable() bool {
	if x != nil && x.Editable != nil {
		return *x.Editable
	}
	return false
}

var File_materialization_proto protoreflect.FileDescriptor

const file_materialization_proto_rawDesc = "" +
	"\n" +
	"\x15materialization.proto\x12\x1amassive.materialization.v0\"\xae\x02\n" +
	"\x13MaterializationSpec\x12*\n" +
	"\x0eschema_version\x18\x01 \x01(\rH\x00R\rschemaVersion\x88\x01\x01\x12 \n" +
	"\tspec_hash\x18\x02 \x01(\tH\x01R\bspecHash\x88\x01\x01\x12T\n" +
	"\fenvironments\x18\x03 \x03(\v20.massive.materialization.v0.EnvironmentSelectionR\fenvironments\x12R\n" +
	"\x0fsource_archives\x18\x04 \x03(\v2).massive.materialization.v0.SourceArchiveR\x0esourceArchivesB\x11\n" +
	"\x0f_schema_versionB\f\n" +
	"\n" +
	"_spec_hash\"\xd2\x01\n" +
	"\x14EnvironmentSelection\x12,\n" +
	"\x0fenvironment_ref\x18\x01 \x01(\tH\x00R\x0eenvironmentRef\x88\x01\x01\x12a\n" +
	"\x12existing_container\x18\x02 \x01(\v2-.massive.materialization.v0.ExistingContainerH\x01R\x11existingContainer\x88\x01\x01B\x12\n" +
	"\x10_environment_refB\x15\n" +
	"\x13_existing_container\"f\n" +
	"\x11ExistingContainer\x12\x19\n" +
	"\x05image\x18\x01 \x01(\tH\x00R\x05image\x88\x01\x01\x12\x1f\n" +
	"\bplatform\x18\x02 \x01(\tH\x01R\bplatform\x88\x01\x01B\b\n" +
	"\x06_imageB\v\n" +
	"\t_platform\"\x81\x01\n" +
	"\rSourceArchive\x12&\n" +
	"\fpackage_hash\x18\x01 \x01(\tH\x00R\vpackageHash\x88\x01\x01\x12&\n" +
	"\farchive_hash\x18\x02 \x01(\tH\x01R\varchiveHash\x88\x01\x01B\x0f\n" +
	"\r_package_hashB\x0f\n" +
	"\r_archive_hash\"\x89\x04\n" +
	"\x17MaterializationManifest\x12*\n" +
	"\x0eschema_version\x18\x01 \x01(\rH\x00R\rschemaVersion\x88\x01\x01\x12(\n" +
	"\rmanifest_hash\x18\x02 \x01(\tH\x01R\fmanifestHash\x88\x01\x01\x12 \n" +
	"\tspec_hash\x18\x03 \x01(\tH\x02R\bspecHash\x88\x01\x01\x12V\n" +
	"\fenvironments\x18\x04 \x03(\v22.massive.materialization.v0.EnvironmentRealizationR\fenvironments\x12R\n" +
	"\x0fsource_archives\x18\x05 \x03(\v2).massive.materialization.v0.SourceArchiveR\x0esourceArchives\x120\n" +
	"\x11materializer_name\x18\x06 \x01(\tH\x03R\x10materializerName\x88\x01\x01\x126\n" +
	"\x14materializer_version\x18\a \x01(\tH\x04R\x13materializerVersion\x88\x01\x01B\x11\n" +
	"\x0f_schema_versionB\x10\n" +
	"\x0e_manifest_hashB\f\n" +
	"\n" +
	"_spec_hashB\x14\n" +
	"\x12_materializer_nameB\x17\n" +
	"\x15_materializer_version\"\x86\x03\n" +
	"\x16EnvironmentRealization\x12,\n" +
	"\x0fenvironment_ref\x18\x01 \x01(\tH\x00R\x0eenvironmentRef\x88\x01\x01\x12.\n" +
	"\x10realization_hash\x18\x02 \x01(\tH\x01R\x0frealizationHash\x88\x01\x01\x12a\n" +
	"\x12existing_container\x18\x03 \x01(\v2-.massive.materialization.v0.ExistingContainerH\x02R\x11existingContainer\x88\x01\x01\x12Z\n" +
	"\fverification\x18\x04 \x01(\x0e21.massive.materialization.v0.ContainerVerificationH\x03R\fverification\x88\x01\x01B\x12\n" +
	"\x10_environment_refB\x13\n" +
	"\x11_realization_hashB\x15\n" +
	"\x13_existing_containerB\x0f\n" +
	"\r_verification\"\xb2\x03\n" +
	"\x13RealizedEnvironment\x12*\n" +
	"\x0eschema_version\x18\x01 \x01(\rH\x00R\rschemaVersion\x88\x01\x01\x12.\n" +
	"\x10requirement_hash\x18\x02 \x01(\tH\x01R\x0frequirementHash\x88\x01\x01\x12.\n" +
	"\x10realization_hash\x18\x03 \x01(\tH\x02R\x0frealizationHash\x88\x01\x01\x12T\n" +
	"\vrequirement\x18\x04 \x01(\v2-.massive.materialization.v0.PythonRequirementH\x03R\vrequirement\x88\x01\x01\x12\\\n" +
	"\vrealization\x18\x05 \x01(\v25.massive.materialization.v0.ExistingPythonRealizationH\x04R\vrealization\x88\x01\x01B\x11\n" +
	"\x0f_schema_versionB\x13\n" +
	"\x11_requirement_hashB\x13\n" +
	"\x11_realization_hashB\x0e\n" +
	"\f_requirementB\x0e\n" +
	"\f_realization\"\xa9\x01\n" +
	"\x11PythonRequirement\x12,\n" +
	"\x0frequires_python\x18\x01 \x01(\tH\x00R\x0erequiresPython\x88\x01\x01\x12 \n" +
	"\tlock_hash\x18\x02 \x01(\tH\x01R\blockHash\x88\x01\x01\x12\"\n" +
	"\fdependencies\x18\x03 \x03(\tR\fdependenciesB\x12\n" +
	"\x10_requires_pythonB\f\n" +
	"\n" +
	"_lock_hash\"\xaf\x05\n" +
	"\x19ExistingPythonRealization\x12+\n" +
	"\x0eimplementation\x18\x01 \x01(\tH\x00R\x0eimplementation\x88\x01\x01\x12*\n" +
	"\x0epython_version\x18\x02 \x01(\tH\x01R\rpythonVersion\x88\x01\x01\x12 \n" +
	"\tcache_tag\x18\x03 \x01(\tH\x02R\bcacheTag\x88\x01\x01\x122\n" +
	"\x12sysconfig_platform\x18\x04 \x01(\tH\x03R\x11sysconfigPlatform\x88\x01\x01\x12\x13\n" +
	"\x02os\x18\x05 \x01(\tH\x04R\x02os\x88\x01\x01\x12\x17\n" +
	"\x04arch\x18\x06 \x01(\tH\x05R\x04arch\x88\x01\x01\x12W\n" +
	"\rdistributions\x18\a \x03(\v21.massive.materialization.v0.InstalledDistributionR\rdistributions\x120\n" +
	"\x11materializer_name\x18\b \x01(\tH\x06R\x10materializerName\x88\x01\x01\x126\n" +
	"\x14materializer_version\x18\t \x01(\tH\aR\x13materializerVersion\x88\x01\x01\x12W\n" +
	"\fverification\x18\n" +
	" \x01(\x0e2..massive.materialization.v0.PythonVerificationH\bR\fverification\x88\x01\x01B\x11\n" +
	"\x0f_implementationB\x11\n" +
	"\x0f_python_versionB\f\n" +
	"\n" +
	"_cache_tagB\x15\n" +
	"\x13_sysconfig_platformB\x05\n" +
	"\x03_osB\a\n" +
	"\x05_archB\x14\n" +
	"\x12_materializer_nameB\x17\n" +
	"\x15_materializer_versionB\x0f\n" +
	"\r_verification\"\xba\x01\n" +
	"\x15InstalledDistribution\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tH\x01R\aversion\x88\x01\x01\x12\x1b\n" +
	"\x06direct\x18\x03 \x01(\bH\x02R\x06direct\x88\x01\x01\x12\x1f\n" +
	"\beditable\x18\x04 \x01(\bH\x03R\beditable\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_versionB\t\n" +
	"\a_directB\v\n" +
	"\t_editable*Z\n" +
	"\x15ContainerVerification\x12&\n" +
	"\"CONTAINER_VERIFICATION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PINNED_REFERENCE_ONLY\x10\x01*\x83\x01\n" +
	"\x12PythonVerification\x12#\n" +
	"\x1fPYTHON_VERIFICATION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOCK_SYNC_CHECKED\x10\x01\x12!\n" +
	"\x1dDIRECT_REQUIREMENTS_SATISFIED\x10\x02\x12\x0e\n" +
	"\n" +
	"UNDECLARED\x10\x03BSZQgithub.com/Sly1029/massive/conformance/schema/materializationpb;materializationpbb\x06proto3"

var (
	file_materialization_proto_rawDescOnce sync.Once
	file_materialization_proto_rawDescData []byte
)

func file_materialization_proto_rawDescGZIP() []byte {
	file_materialization_proto_rawDescOnce.Do(func() {
		file_materialization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_materialization_proto_rawDesc), len(file_materialization_proto_rawDesc)))
	})
	return file_materialization_proto_rawDescData
}

var file_materialization_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_materialization_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_materialization_proto_goTypes = []any{
	(ContainerVerification)(0),        // 0: massive.materialization.v0.ContainerVerification
	(PythonVerification)(0),           // 1: massive.materialization.v0.PythonVerification
	(*MaterializationSpec)(nil),       // 2: massive.materialization.v0.MaterializationSpec
	(*EnvironmentSelection)(nil),      // 3: massive.materialization.v0.EnvironmentSelection
	(*ExistingContainer)(nil),         // 4: massive.materialization.v0.ExistingContainer
	(*SourceArchive)(nil),             // 5: massive.materialization.v0.SourceArchive
	(*MaterializationManifest)(nil),   // 6: massive.materialization.v0.MaterializationManifest
	(*EnvironmentRealization)(nil),    // 7: massive.materialization.v0.EnvironmentRealization
	(*RealizedEnvironment)(nil),       // 8: massive.materialization.v0.RealizedEnvironment
	(*PythonRequirement)(nil),         // 9: massive.materialization.v0.PythonRequirement
	(*ExistingPythonRealization)(nil), // 10: massive.materialization.v0.ExistingPythonRealization
	(*InstalledDistribution)(nil),     // 11: massive.materialization.v0.InstalledDistribution
}
var file_materialization_proto_depIdxs = []int32{
	3,  // 0: massive.materialization.v0.MaterializationSpec.environments:type_name -> massive.materialization.v0.EnvironmentSelection
	5,  // 1: massive.materialization.v0.MaterializationSpec.source_archives:type_name -> massive.materialization.v0.SourceArchive
	4,  // 2: massive.materialization.v0.EnvironmentSelection.existing_container:type_name -> massive.materialization.v0.ExistingContainer
	7,  // 3: massive.materialization.v0.MaterializationManifest.environments:type_name -> massive.materialization.v0.EnvironmentRealization
	5,  // 4: massive.materialization.v0.MaterializationManifest.source_archives:type_name -> massive.materialization.v0.SourceArchive
	4,  // 5: massive.materialization.v0.EnvironmentRealization.existing_container:type_name -> massive.materialization.v0.ExistingContainer
	0,  // 6: massive.materialization.v0.EnvironmentRealization.verification:type_name -> massive.materialization.v0.ContainerVerification
	9,  // 7: massive.materialization.v0.RealizedEnvironment.requirement:type_name -> massive.materialization.v0.PythonRequirement
	10, // 8: massive.materialization.v0.RealizedEnvironment.realization:type_name -> massive.materialization.v0.ExistingPythonRealization
	11, // 9: massive.materialization.v0.ExistingPythonRealization.distributions:type_name -> massive.materialization.v0.InstalledDistribution
	1,  // 10: massive.materialization.v0.ExistingPythonRealization.verification:type_name -> massive.materialization.v0.PythonVerification
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_materialization_proto_init() }
func file_materialization_proto_init() {
	if File_materialization_proto != nil {
		return
	}
	file_materialization_proto_msgTypes[0].OneofWrappers = []any{}
	file_materialization_proto_msgTypes[1].OneofWrappers = []any{}
	file_materialization_proto_msgTypes[2].OneofWrappers = []any{}
	file_materialization_proto_msgTypes[3].OneofWrappers = []any{}
	file_materialization_proto_msgTypes[4].OneofWrappers = []any{}
	file_materialization_proto_msgTypes[5].OneofWrappers = []any{}
	file_materialization_proto_msgTypes[6].OneofWrappers = []any{}
	file_materialization_proto_msgTypes[7].OneofWrappers = []any{}
	file_materialization_proto_msgTypes[8].OneofWrappers = []any{}
	file_materialization_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_materialization_proto_rawDesc), len(file_materialization_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_materialization_proto_goTypes,
		DependencyIndexes: file_materialization_proto_depIdxs,
		EnumInfos:         file_materialization_proto_enumTypes,
		MessageInfos:      file_materialization_proto_msgTypes,
	}.Build()
	File_materialization_proto = out.File
	file_materialization_proto_goTypes = nil
	file_materialization_proto_depIdxs = nil
}
