// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: bundle-manifest.proto

package planpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetBundleManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion *uint32                `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3,oneof" json:"schema_version,omitempty"`
	Target        *string                `protobuf:"bytes,2,opt,name=target,proto3,oneof" json:"target,omitempty"`
	PlanHash      *string                `protobuf:"bytes,3,opt,name=plan_hash,json=planHash,proto3,oneof" json:"plan_hash,omitempty"`
	BundleHash    *string                `protobuf:"bytes,4,opt,name=bundle_hash,json=bundleHash,proto3,oneof" json:"bundle_hash,omitempty"`
	Files         []*EmittedFile         `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	Validations   []*ValidationResult    `protobuf:"bytes,6,rep,name=validations,proto3" json:"validations,omitempty"`
	Provenance    *BundleProvenance      `protobuf:"bytes,7,opt,name=provenance,proto3,oneof" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetBundleManifest) Reset() {
	*x = TargetBundleManifest{}
	mi := &file_bundle_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetBundleManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetBundleManifest) ProtoMessage() {}

func (x *TargetBundleManifest) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetBundleManifest.ProtoReflect.Descriptor instead.
func (*TargetBundleManifest) Descriptor() ([]byte, []int) {
	return file_bundle_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *TargetBundleManifest) GetSchemaVersion() uint32 {
	if x != nil && x.SchemaVersion != nil {
		return *x.SchemaVersion
	}
	return 0
}

func (x *TargetBundleManifest) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *TargetBundleManifest) GetPlanHash() string {
	if x != nil && x.PlanHash != nil {
		return *x.PlanHash
	}
	return ""
}

func (x *TargetBundleManifest) GetBundleHash() string {
	if x != nil && x.BundleHash != nil {
		return *x.BundleHash
	}
	return ""
}

func (x *TargetBundleManifest) GetFiles() []*EmittedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *TargetBundleManifest) GetValidations() []*ValidationResult {
	if x != nil {
		return x.Validations
	}
	return nil
}

func (x *TargetBundleManifest) GetProvenance() *BundleProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type EmittedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Artifact      *ArtifactRef           `protobuf:"bytes,2,opt,name=artifact,proto3,oneof" json:"artifact,omitempty"`
	Role          *string                `protobuf:"bytes,3,opt,name=role,proto3,oneof" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmittedFile) Reset() {
	*x = EmittedFile{}
	mi := &file_bundle_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmittedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmittedFile) ProtoMessage() {}

func (x *EmittedFile) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmittedFile.ProtoReflect.Descriptor instead.
func (*EmittedFile) Descriptor() ([]byte, []int) {
	return file_bundle_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *EmittedFile) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *EmittedFile) GetArtifact() *ArtifactRef {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *EmittedFile) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

type ValidationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Passed        *bool                  `protobuf:"varint,2,opt,name=passed,proto3,oneof" json:"passed,omitempty"`
	Diagnostic    *string                `protobuf:"bytes,3,opt,name=diagnostic,proto3,oneof" json:"diagnostic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_bundle_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_bundle_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationResult) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ValidationResult) GetPassed() bool {
	if x != nil && x.Passed != nil {
		return *x.Passed
	}
	return false
}

func (x *ValidationResult) GetDiagnostic() string {
	if x != nil && x.Diagnostic != nil {
		return *x.Diagnostic
	}
	return ""
}

type BundleProvenance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompilerName    *string                `protobuf:"bytes,1,opt,name=compiler_name,json=compilerName,proto3,oneof" json:"compiler_name,omitempty"`
	CompilerVersion *string                `protobuf:"bytes,2,opt,name=compiler_version,json=compilerVersion,proto3,oneof" json:"compiler_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BundleProvenance) Reset() {
	*x = BundleProvenance{}
	mi := &file_bundle_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleProvenance) ProtoMessage() {}

func (x *BundleProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleProvenance.ProtoReflect.Descriptor instead.
func (*BundleProvenance) Descriptor() ([]byte, []int) {
	return file_bundle_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *BundleProvenance) GetCompilerName() string {
	if x != nil && x.CompilerName != nil {
		return *x.CompilerName
	}
	return ""
}

func (x *BundleProvenance) GetCompilerVersion() string {
	if x != nil && x.CompilerVersion != nil {
		return *x.CompilerVersion
	}
	return ""
}

var File_bundle_manifest_proto protoreflect.FileDescriptor

const file_bundle_manifest_proto_rawDesc = "" +
	"\n" +
	"\x15bundle-manifest.proto\x12\x0fmassive.plan.v0\x1a\x13workflow-plan.proto\"\xb3\x03\n" +
	"\x14TargetBundleManifest\x12*\n" +
	"\x0eschema_version\x18\x01 \x01(\rH\x00R\rschemaVersion\x88\x01\x01\x12\x1b\n" +
	"\x06target\x18\x02 \x01(\tH\x01R\x06target\x88\x01\x01\x12 \n" +
	"\tplan_hash\x18\x03 \x01(\tH\x02R\bplanHash\x88\x01\x01\x12$\n" +
	"\vbundle_hash\x18\x04 \x01(\tH\x03R\n" +
	"bundleHash\x88\x01\x01\x122\n" +
	"\x05files\x18\x05 \x03(\v2\x1c.massive.plan.v0.EmittedFileR\x05files\x12C\n" +
	"\vvalidations\x18\x06 \x03(\v2!.massive.plan.v0.ValidationResultR\vvalidations\x12F\n" +
	"\n" +
	"provenance\x18\a \x01(\v2!.massive.plan.v0.BundleProvenanceH\x04R\n" +
	"provenance\x88\x01\x01B\x11\n" +
	"\x0f_schema_versionB\t\n" +
	"\a_targetB\f\n" +
	"\n" +
	"_plan_hashB\x0e\n" +
	"\f_bundle_hashB\r\n" +
	"\v_provenance\"\x9d\x01\n" +
	"\vEmittedFile\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x88\x01\x01\x12=\n" +
	"\bartifact\x18\x02 \x01(\v2\x1c.massive.plan.v0.ArtifactRefH\x01R\bartifact\x88\x01\x01\x12\x17\n" +
	"\x04role\x18\x03 \x01(\tH\x02R\x04role\x88\x01\x01B\a\n" +
	"\x05_pathB\v\n" +
	"\t_artifactB\a\n" +
	"\x05_role\"\x90\x01\n" +
	"\x10ValidationResult\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06passed\x18\x02 \x01(\bH\x01R\x06passed\x88\x01\x01\x12#\n" +
	"\n" +
	"diagnostic\x18\x03 \x01(\tH\x02R\n" +
	"diagnostic\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_passedB\r\n" +
	"\v_diagnostic\"\x93\x01\n" +
	"\x10BundleProvenance\x12(\n" +
	"\rcompiler_name\x18\x01 \x01(\tH\x00R\fcompilerName\x88\x01\x01\x12.\n" +
	"\x10compiler_version\x18\x02 \x01(\tH\x01R\x0fcompilerVersion\x88\x01\x01B\x10\n" +
	"\x0e_compiler_nameB\x13\n" +
	"\x11_compiler_versionB=Z;github.com/Sly1029/massive/conformance/schema/planpb;planpbb\x06proto3"

var (
	file_bundle_manifest_proto_rawDescOnce sync.Once
	file_bundle_manifest_proto_rawDescData []byte
)

func file_bundle_manifest_proto_rawDescGZIP() []byte {
	file_bundle_manifest_proto_rawDescOnce.Do(func() {
		file_bundle_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bundle_manifest_proto_rawDesc), len(file_bundle_manifest_proto_rawDesc)))
	})
	return file_bundle_manifest_proto_rawDescData
}

var file_bundle_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bundle_manifest_proto_goTypes = []any{
	(*TargetBundleManifest)(nil), // 0: massive.plan.v0.TargetBundleManifest
	(*EmittedFile)(nil),          // 1: massive.plan.v0.EmittedFile
	(*ValidationResult)(nil),     // 2: massive.plan.v0.ValidationResult
	(*BundleProvenance)(nil),     // 3: massive.plan.v0.BundleProvenance
	(*ArtifactRef)(nil),          // 4: massive.plan.v0.ArtifactRef
}
var file_bundle_manifest_proto_depIdxs = []int32{
	1, // 0: massive.plan.v0.TargetBundleManifest.files:type_name -> massive.plan.v0.EmittedFile
	2, // 1: massive.plan.v0.TargetBundleManifest.validations:type_name -> massive.plan.v0.ValidationResult
	3, // 2: massive.plan.v0.TargetBundleManifest.provenance:type_name -> massive.plan.v0.BundleProvenance
	4, // 3: massive.plan.v0.EmittedFile.artifact:type_name -> massive.plan.v0.ArtifactRef
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bundle_manifest_proto_init() }
func file_bundle_manifest_proto_init() {
	if File_bundle_manifest_proto != nil {
		return
	}
	file_workflow_plan_proto_init()
	file_bundle_manifest_proto_msgTypes[0].OneofWrappers = []any{}
	file_bundle_manifest_proto_msgTypes[1].OneofWrappers = []any{}
	file_bundle_manifest_proto_msgTypes[2].OneofWrappers = []any{}
	file_bundle_manifest_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bundle_manifest_proto_rawDesc), len(file_bundle_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bundle_manifest_proto_goTypes,
		DependencyIndexes: file_bundle_manifest_proto_depIdxs,
		MessageInfos:      file_bundle_manifest_proto_msgTypes,
	}.Build()
	File_bundle_manifest_proto = out.File
	file_bundle_manifest_proto_goTypes = nil
	file_bundle_manifest_proto_depIdxs = nil
}
