// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: workflow-plan.proto

package planpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Hash          *string                `protobuf:"bytes,2,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
	ContentType   *string                `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_workflow_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactRef) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ArtifactRef) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

func (x *ArtifactRef) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

type WorkflowPlan struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	SchemaVersion      *uint32                    `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3,oneof" json:"schema_version,omitempty"`
	PlanHash           *string                    `protobuf:"bytes,2,opt,name=plan_hash,json=planHash,proto3,oneof" json:"plan_hash,omitempty"`
	SpecHash           *string                    `protobuf:"bytes,3,opt,name=spec_hash,json=specHash,proto3,oneof" json:"spec_hash,omitempty"`
	Graph              *GraphIR                   `protobuf:"bytes,4,opt,name=graph,proto3,oneof" json:"graph,omitempty"`
	Schemas            []*SchemaEntry             `protobuf:"bytes,5,rep,name=schemas,proto3" json:"schemas,omitempty"`
	Symbols            []*SymbolEntry             `protobuf:"bytes,6,rep,name=symbols,proto3" json:"symbols,omitempty"`
	SourcePackages     []*SourcePackageRef        `protobuf:"bytes,7,rep,name=source_packages,json=sourcePackages,proto3" json:"source_packages,omitempty"`
	Environments       []*MaterializedEnvironment `protobuf:"bytes,8,rep,name=environments,proto3" json:"environments,omitempty"`
	Contracts          []*ExecutionContract       `protobuf:"bytes,9,rep,name=contracts,proto3" json:"contracts,omitempty"`
	Targets            []*TargetPlan              `protobuf:"bytes,10,rep,name=targets,proto3" json:"targets,omitempty"`
	DatastoreManifests []*ArtifactRef             `protobuf:"bytes,11,rep,name=datastore_manifests,json=datastoreManifests,proto3" json:"datastore_manifests,omitempty"`
	Provenance         *CompilerProvenance        `protobuf:"bytes,12,opt,name=provenance,proto3,oneof" json:"provenance,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowPlan) Reset() {
	*x = WorkflowPlan{}
	mi := &file_workflow_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowPlan) ProtoMessage() {}

func (x *WorkflowPlan) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowPlan.ProtoReflect.Descriptor instead.
func (*WorkflowPlan) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowPlan) GetSchemaVersion() uint32 {
	if x != nil && x.SchemaVersion != nil {
		return *x.SchemaVersion
	}
	return 0
}

func (x *WorkflowPlan) GetPlanHash() string {
	if x != nil && x.PlanHash != nil {
		return *x.PlanHash
	}
	return ""
}

func (x *WorkflowPlan) GetSpecHash() string {
	if x != nil && x.SpecHash != nil {
		return *x.SpecHash
	}
	return ""
}

func (x *WorkflowPlan) GetGraph() *GraphIR {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *WorkflowPlan) GetSchemas() []*SchemaEntry {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *WorkflowPlan) GetSymbols() []*SymbolEntry {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *WorkflowPlan) GetSourcePackages() []*SourcePackageRef {
	if x != nil {
		return x.SourcePackages
	}
	return nil
}

func (x *WorkflowPlan) GetEnvironments() []*MaterializedEnvironment {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *WorkflowPlan) GetContracts() []*ExecutionContract {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *WorkflowPlan) GetTargets() []*TargetPlan {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *WorkflowPlan) GetDatastoreManifests() []*ArtifactRef {
	if x != nil {
		return x.DatastoreManifests
	}
	return nil
}

func (x *WorkflowPlan) GetProvenance() *CompilerProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type GraphIR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowName  *string                `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3,oneof" json:"workflow_name,omitempty"`
	InputSchema   *string                `protobuf:"bytes,2,opt,name=input_schema,json=inputSchema,proto3,oneof" json:"input_schema,omitempty"`
	OutputSchema  *string                `protobuf:"bytes,3,opt,name=output_schema,json=outputSchema,proto3,oneof" json:"output_schema,omitempty"`
	StartNode     *string                `protobuf:"bytes,4,opt,name=start_node,json=startNode,proto3,oneof" json:"start_node,omitempty"`
	EndNode       *string                `protobuf:"bytes,5,opt,name=end_node,json=endNode,proto3,oneof" json:"end_node,omitempty"`
	Nodes         []*GraphNode           `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,7,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphIR) Reset() {
	*x = GraphIR{}
	mi := &file_workflow_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphIR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphIR) ProtoMessage() {}

func (x *GraphIR) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphIR.ProtoReflect.Descriptor instead.
func (*GraphIR) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{2}
}

func (x *GraphIR) GetWorkflowName() string {
	if x != nil && x.WorkflowName != nil {
		return *x.WorkflowName
	}
	return ""
}

func (x *GraphIR) GetInputSchema() string {
	if x != nil && x.InputSchema != nil {
		return *x.InputSchema
	}
	return ""
}

func (x *GraphIR) GetOutputSchema() string {
	if x != nil && x.OutputSchema != nil {
		return *x.OutputSchema
	}
	return ""
}

func (x *GraphIR) GetStartNode() string {
	if x != nil && x.StartNode != nil {
		return *x.StartNode
	}
	return ""
}

func (x *GraphIR) GetEndNode() string {
	if x != nil && x.EndNode != nil {
		return *x.EndNode
	}
	return ""
}

func (x *GraphIR) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphIR) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GraphNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// "start", "step", or "end". Fan-in steps list their merged upstream step
	// ids in merge_inputs; plain steps omit it (empty repeated fields are not
	// serialized).
	Kind          *string  `protobuf:"bytes,2,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	InputSchema   *string  `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3,oneof" json:"input_schema,omitempty"`
	OutputSchema  *string  `protobuf:"bytes,4,opt,name=output_schema,json=outputSchema,proto3,oneof" json:"output_schema,omitempty"`
	SymbolRef     *string  `protobuf:"bytes,5,opt,name=symbol_ref,json=symbolRef,proto3,oneof" json:"symbol_ref,omitempty"`
	ContractRef   *string  `protobuf:"bytes,6,opt,name=contract_ref,json=contractRef,proto3,oneof" json:"contract_ref,omitempty"`
	MergeInputs   []string `protobuf:"bytes,7,rep,name=merge_inputs,json=mergeInputs,proto3" json:"merge_inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_workflow_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{3}
}

func (x *GraphNode) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *GraphNode) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *GraphNode) GetInputSchema() string {
	if x != nil && x.InputSchema != nil {
		return *x.InputSchema
	}
	return ""
}

func (x *GraphNode) GetOutputSchema() string {
	if x != nil && x.OutputSchema != nil {
		return *x.OutputSchema
	}
	return ""
}

func (x *GraphNode) GetSymbolRef() string {
	if x != nil && x.SymbolRef != nil {
		return *x.SymbolRef
	}
	return ""
}

func (x *GraphNode) GetContractRef() string {
	if x != nil && x.ContractRef != nil {
		return *x.ContractRef
	}
	return ""
}

func (x *GraphNode) GetMergeInputs() []string {
	if x != nil {
		return x.MergeInputs
	}
	return nil
}

type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *string                `protobuf:"bytes,1,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *string                `protobuf:"bytes,2,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_workflow_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{4}
}

func (x *GraphEdge) GetFrom() string {
	if x != nil && x.From != nil {
		return *x.From
	}
	return ""
}

func (x *GraphEdge) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

type SchemaEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          *string                `protobuf:"bytes,1,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
	CanonicalJson *string                `protobuf:"bytes,2,opt,name=canonical_json,json=canonicalJson,proto3,oneof" json:"canonical_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaEntry) Reset() {
	*x = SchemaEntry{}
	mi := &file_workflow_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaEntry) ProtoMessage() {}

func (x *SchemaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaEntry.ProtoReflect.Descriptor instead.
func (*SchemaEntry) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{5}
}

func (x *SchemaEntry) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

func (x *SchemaEntry) GetCanonicalJson() string {
	if x != nil && x.CanonicalJson != nil {
		return *x.CanonicalJson
	}
	return ""
}

type SymbolEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolRef     *string                `protobuf:"bytes,1,opt,name=symbol_ref,json=symbolRef,proto3,oneof" json:"symbol_ref,omitempty"`
	PackageId     *string                `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3,oneof" json:"package_id,omitempty"`
	Language      *string                `protobuf:"bytes,3,opt,name=language,proto3,oneof" json:"language,omitempty"`
	Module        *string                `protobuf:"bytes,4,opt,name=module,proto3,oneof" json:"module,omitempty"`
	Export        *string                `protobuf:"bytes,5,opt,name=export,proto3,oneof" json:"export,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolEntry) Reset() {
	*x = SymbolEntry{}
	mi := &file_workflow_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolEntry) ProtoMessage() {}

func (x *SymbolEntry) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolEntry.ProtoReflect.Descriptor instead.
func (*SymbolEntry) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{6}
}

func (x *SymbolEntry) GetSymbolRef() string {
	if x != nil && x.SymbolRef != nil {
		return *x.SymbolRef
	}
	return ""
}

func (x *SymbolEntry) GetPackageId() string {
	if x != nil && x.PackageId != nil {
		return *x.PackageId
	}
	return ""
}

func (x *SymbolEntry) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *SymbolEntry) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

func (x *SymbolEntry) GetExport() string {
	if x != nil && x.Export != nil {
		return *x.Export
	}
	return ""
}

type SourcePackageRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     *string                `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3,oneof" json:"package_id,omitempty"`
	Language      *string                `protobuf:"bytes,2,opt,name=language,proto3,oneof" json:"language,omitempty"`
	PackageHash   *string                `protobuf:"bytes,3,opt,name=package_hash,json=packageHash,proto3,oneof" json:"package_hash,omitempty"`
	Manifest      *ArtifactRef           `protobuf:"bytes,4,opt,name=manifest,proto3,oneof" json:"manifest,omitempty"`
	SourceArchive *ArtifactRef           `protobuf:"bytes,5,opt,name=source_archive,json=sourceArchive,proto3,oneof" json:"source_archive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcePackageRef) Reset() {
	*x = SourcePackageRef{}
	mi := &file_workflow_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcePackageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcePackageRef) ProtoMessage() {}

func (x *SourcePackageRef) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcePackageRef.ProtoReflect.Descriptor instead.
func (*SourcePackageRef) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{7}
}

func (x *SourcePackageRef) GetPackageId() string {
	if x != nil && x.PackageId != nil {
		return *x.PackageId
	}
	return ""
}

func (x *SourcePackageRef) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *SourcePackageRef) GetPackageHash() string {
	if x != nil && x.PackageHash != nil {
		return *x.PackageHash
	}
	return ""
}

func (x *SourcePackageRef) GetManifest() *ArtifactRef {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *SourcePackageRef) GetSourceArchive() *ArtifactRef {
	if x != nil {
		return x.SourceArchive
	}
	return nil
}

type MaterializedEnvironment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvRef        *string                `protobuf:"bytes,1,opt,name=env_ref,json=envRef,proto3,oneof" json:"env_ref,omitempty"`
	SpecHash      *string                `protobuf:"bytes,2,opt,name=spec_hash,json=specHash,proto3,oneof" json:"spec_hash,omitempty"`
	Kind          *string                `protobuf:"bytes,3,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	Local         *ArtifactRef           `protobuf:"bytes,4,opt,name=local,proto3,oneof" json:"local,omitempty"`
	Container     *ContainerRuntime      `protobuf:"bytes,5,opt,name=container,proto3,oneof" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializedEnvironment) Reset() {
	*x = MaterializedEnvironment{}
	mi := &file_workflow_plan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedEnvironment) ProtoMessage() {}

func (x *MaterializedEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializedEnvironment.ProtoReflect.Descriptor instead.
func (*MaterializedEnvironment) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{8}
}

func (x *MaterializedEnvironment) GetEnvRef() string {
	if x != nil && x.EnvRef != nil {
		return *x.EnvRef
	}
	return ""
}

func (x *MaterializedEnvironment) GetSpecHash() string {
	if x != nil && x.SpecHash != nil {
		return *x.SpecHash
	}
	return ""
}

func (x *MaterializedEnvironment) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *MaterializedEnvironment) GetLocal() *ArtifactRef {
	if x != nil {
		return x.Local
	}
	return nil
}

func (x *MaterializedEnvironment) GetContainer() *ContainerRuntime {
	if x != nil {
		return x.Container
	}
	return nil
}

type ContainerRuntime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *string                `protobuf:"bytes,1,opt,name=image,proto3,oneof" json:"image,omitempty"`
	SourceFetch   *ArtifactRef           `protobuf:"bytes,2,opt,name=source_fetch,json=sourceFetch,proto3,oneof" json:"source_fetch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRuntime) Reset() {
	*x = ContainerRuntime{}
	mi := &file_workflow_plan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRuntime) ProtoMessage() {}

func (x *ContainerRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRuntime.ProtoReflect.Descriptor instead.
func (*ContainerRuntime) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{9}
}

func (x *ContainerRuntime) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *ContainerRuntime) GetSourceFetch() *ArtifactRef {
	if x != nil {
		return x.SourceFetch
	}
	return nil
}

type ExecutionContract struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContractRef    *string                `protobuf:"bytes,1,opt,name=contract_ref,json=contractRef,proto3,oneof" json:"contract_ref,omitempty"`
	EnvironmentRef *string                `protobuf:"bytes,2,opt,name=environment_ref,json=environmentRef,proto3,oneof" json:"environment_ref,omitempty"`
	Resources      *ResourceRequirements  `protobuf:"bytes,3,opt,name=resources,proto3,oneof" json:"resources,omitempty"`
	Secrets        []*SecretRef           `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty"`
	Network        *NetworkPolicy         `protobuf:"bytes,5,opt,name=network,proto3,oneof" json:"network,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionContract) Reset() {
	*x = ExecutionContract{}
	mi := &file_workflow_plan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContract) ProtoMessage() {}

func (x *ExecutionContract) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContract.ProtoReflect.Descriptor instead.
func (*ExecutionContract) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{10}
}

func (x *ExecutionContract) GetContractRef() string {
	if x != nil && x.ContractRef != nil {
		return *x.ContractRef
	}
	return ""
}

func (x *ExecutionContract) GetEnvironmentRef() string {
	if x != nil && x.EnvironmentRef != nil {
		return *x.EnvironmentRef
	}
	return ""
}

func (x *ExecutionContract) GetResources() *ResourceRequirements {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ExecutionContract) GetSecrets() []*SecretRef {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ExecutionContract) GetNetwork() *NetworkPolicy {
	if x != nil {
		return x.Network
	}
	return nil
}

type ResourceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *string                `protobuf:"bytes,1,opt,name=cpu,proto3,oneof" json:"cpu,omitempty"`
	Memory        *string                `protobuf:"bytes,2,opt,name=memory,proto3,oneof" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	mi := &file_workflow_plan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceRequirements) GetCpu() string {
	if x != nil && x.Cpu != nil {
		return *x.Cpu
	}
	return ""
}

func (x *ResourceRequirements) GetMemory() string {
	if x != nil && x.Memory != nil {
		return *x.Memory
	}
	return ""
}

type SecretRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Ref           *string                `protobuf:"bytes,2,opt,name=ref,proto3,oneof" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRef) Reset() {
	*x = SecretRef{}
	mi := &file_workflow_plan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRef) ProtoMessage() {}

func (x *SecretRef) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRef.ProtoReflect.Descriptor instead.
func (*SecretRef) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{12}
}

func (x *SecretRef) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SecretRef) GetRef() string {
	if x != nil && x.Ref != nil {
		return *x.Ref
	}
	return ""
}

type NetworkPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "none", "declared", or "any". When "declared", hosts lists the declared
	// egress destinations.
	Egress        *string  `protobuf:"bytes,1,opt,name=egress,proto3,oneof" json:"egress,omitempty"`
	Hosts         []string `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	mi := &file_workflow_plan_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{13}
}

func (x *NetworkPolicy) GetEgress() string {
	if x != nil && x.Egress != nil {
		return *x.Egress
	}
	return ""
}

func (x *NetworkPolicy) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type TargetPlan struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           *string                `protobuf:"bytes,1,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	TargetHash     *string                `protobuf:"bytes,2,opt,name=target_hash,json=targetHash,proto3,oneof" json:"target_hash,omitempty"`
	BundleManifest *ArtifactRef           `protobuf:"bytes,3,opt,name=bundle_manifest,json=bundleManifest,proto3,oneof" json:"bundle_manifest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TargetPlan) Reset() {
	*x = TargetPlan{}
	mi := &file_workflow_plan_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetPlan) ProtoMessage() {}

func (x *TargetPlan) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetPlan.ProtoReflect.Descriptor instead.
func (*TargetPlan) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{14}
}

func (x *TargetPlan) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *TargetPlan) GetTargetHash() string {
	if x != nil && x.TargetHash != nil {
		return *x.TargetHash
	}
	return ""
}

func (x *TargetPlan) GetBundleManifest() *ArtifactRef {
	if x != nil {
		return x.BundleManifest
	}
	return nil
}

type CompilerProvenance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompilerName    *string                `protobuf:"bytes,1,opt,name=compiler_name,json=compilerName,proto3,oneof" json:"compiler_name,omitempty"`
	CompilerVersion *string                `protobuf:"bytes,2,opt,name=compiler_version,json=compilerVersion,proto3,oneof" json:"compiler_version,omitempty"`
	SourceSpecHash  *string                `protobuf:"bytes,3,opt,name=source_spec_hash,json=sourceSpecHash,proto3,oneof" json:"source_spec_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompilerProvenance) Reset() {
	*x = CompilerProvenance{}
	mi := &file_workflow_plan_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompilerProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilerProvenance) ProtoMessage() {}

func (x *CompilerProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plan_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilerProvenance.ProtoReflect.Descriptor instead.
func (*CompilerProvenance) Descriptor() ([]byte, []int) {
	return file_workflow_plan_proto_rawDescGZIP(), []int{15}
}

func (x *CompilerProvenance) GetCompilerName() string {
	if x != nil && x.CompilerName != nil {
		return *x.CompilerName
	}
	return ""
}

func (x *CompilerProvenance) GetCompilerVersion() string {
	if x != nil && x.CompilerVersion != nil {
		return *x.CompilerVersion
	}
	return ""
}

func (x *CompilerProvenance) GetSourceSpecHash() string {
	if x != nil && x.SourceSpecHash != nil {
		return *x.SourceSpecHash
	}
	return ""
}

var File_workflow_plan_proto protoreflect.FileDescriptor

const file_workflow_plan_proto_rawDesc = "" +
	"\n" +
	"\x13workflow-plan.proto\x12\x0fmassive.plan.v0\"\x87\x01\n" +
	"\vArtifactRef\x12\x15\n" +
	"\x03key\x18\x01 \x01(\tH\x00R\x03key\x88\x01\x01\x12\x17\n" +
	"\x04hash\x18\x02 \x01(\tH\x01R\x04hash\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\x03 \x01(\tH\x02R\vcontentType\x88\x01\x01B\x06\n" +
	"\x04_keyB\a\n" +
	"\x05_hashB\x0f\n" +
	"\r_content_type\"\x97\x06\n" +
	"\fWorkflowPlan\x12*\n" +
	"\x0eschema_version\x18\x01 \x01(\rH\x00R\rschemaVersion\x88\x01\x01\x12 \n" +
	"\tplan_hash\x18\x02 \x01(\tH\x01R\bplanHash\x88\x01\x01\x12 \n" +
	"\tspec_hash\x18\x03 \x01(\tH\x02R\bspecHash\x88\x01\x01\x123\n" +
	"\x05graph\x18\x04 \x01(\v2\x18.massive.plan.v0.GraphIRH\x03R\x05graph\x88\x01\x01\x126\n" +
	"\aschemas\x18\x05 \x03(\v2\x1c.massive.plan.v0.SchemaEntryR\aschemas\x126\n" +
	"\asymbols\x18\x06 \x03(\v2\x1c.massive.plan.v0.SymbolEntryR\asymbols\x12J\n" +
	"\x0fsource_packages\x18\a \x03(\v2!.massive.plan.v0.SourcePackageRefR\x0esourcePackages\x12L\n" +
	"\fenvironments\x18\b \x03(\v2(.massive.plan.v0.MaterializedEnvironmentR\fenvironments\x12@\n" +
	"\tcontracts\x18\t \x03(\v2\".massive.plan.v0.ExecutionContractR\tcontracts\x125\n" +
	"\atargets\x18\n" +
	" \x03(\v2\x1b.massive.plan.v0.TargetPlanR\atargets\x12M\n" +
	"\x13datastore_manifests\x18\v \x03(\v2\x1c.massive.plan.v0.ArtifactRefR\x12datastoreManifests\x12H\n" +
	"\n" +
	"provenance\x18\f \x01(\v2#.massive.plan.v0.CompilerProvenanceH\x04R\n" +
	"provenance\x88\x01\x01B\x11\n" +
	"\x0f_schema_versionB\f\n" +
	"\n" +
	"_plan_hashB\f\n" +
	"\n" +
	"_spec_hashB\b\n" +
	"\x06_graphB\r\n" +
	"\v_provenance\"\xfe\x02\n" +
	"\aGraphIR\x12(\n" +
	"\rworkflow_name\x18\x01 \x01(\tH\x00R\fworkflowName\x88\x01\x01\x12&\n" +
	"\finput_schema\x18\x02 \x01(\tH\x01R\vinputSchema\x88\x01\x01\x12(\n" +
	"\routput_schema\x18\x03 \x01(\tH\x02R\foutputSchema\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_node\x18\x04 \x01(\tH\x03R\tstartNode\x88\x01\x01\x12\x1e\n" +
	"\bend_node\x18\x05 \x01(\tH\x04R\aendNode\x88\x01\x01\x120\n" +
	"\x05nodes\x18\x06 \x03(\v2\x1a.massive.plan.v0.GraphNodeR\x05nodes\x120\n" +
	"\x05edges\x18\a \x03(\v2\x1a.massive.plan.v0.GraphEdgeR\x05edgesB\x10\n" +
	"\x0e_workflow_nameB\x0f\n" +
	"\r_input_schemaB\x10\n" +
	"\x0e_output_schemaB\r\n" +
	"\v_start_nodeB\v\n" +
	"\t_end_node\"\xcd\x02\n" +
	"\tGraphNode\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04kind\x18\x02 \x01(\tH\x01R\x04kind\x88\x01\x01\x12&\n" +
	"\finput_schema\x18\x03 \x01(\tH\x02R\vinputSchema\x88\x01\x01\x12(\n" +
	"\routput_schema\x18\x04 \x01(\tH\x03R\foutputSchema\x88\x01\x01\x12\"\n" +
	"\n" +
	"symbol_ref\x18\x05 \x01(\tH\x04R\tsymbolRef\x88\x01\x01\x12&\n" +
	"\fcontract_ref\x18\x06 \x01(\tH\x05R\vcontractRef\x88\x01\x01\x12!\n" +
	"\fmerge_inputs\x18\a \x03(\tR\vmergeInputsB\x05\n" +
	"\x03_idB\a\n" +
	"\x05_kindB\x0f\n" +
	"\r_input_schemaB\x10\n" +
	"\x0e_output_schemaB\r\n" +
	"\v_symbol_refB\x0f\n" +
	"\r_contract_ref\"I\n" +
	"\tGraphEdge\x12\x17\n" +
	"\x04from\x18\x01 \x01(\tH\x00R\x04from\x88\x01\x01\x12\x13\n" +
	"\x02to\x18\x02 \x01(\tH\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"n\n" +
	"\vSchemaEntry\x12\x17\n" +
	"\x04hash\x18\x01 \x01(\tH\x00R\x04hash\x88\x01\x01\x12*\n" +
	"\x0ecanonical_json\x18\x02 \x01(\tH\x01R\rcanonicalJson\x88\x01\x01B\a\n" +
	"\x05_hashB\x11\n" +
	"\x0f_canonical_json\"\xf1\x01\n" +
	"\vSymbolEntry\x12\"\n" +
	"\n" +
	"symbol_ref\x18\x01 \x01(\tH\x00R\tsymbolRef\x88\x01\x01\x12\"\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tH\x01R\tpackageId\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x03 \x01(\tH\x02R\blanguage\x88\x01\x01\x12\x1b\n" +
	"\x06module\x18\x04 \x01(\tH\x03R\x06module\x88\x01\x01\x12\x1b\n" +
	"\x06export\x18\x05 \x01(\tH\x04R\x06export\x88\x01\x01B\r\n" +
	"\v_symbol_refB\r\n" +
	"\v_package_idB\v\n" +
	"\t_languageB\t\n" +
	"\a_moduleB\t\n" +
	"\a_export\"\xd5\x02\n" +
	"\x10SourcePackageRef\x12\"\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tH\x00R\tpackageId\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x02 \x01(\tH\x01R\blanguage\x88\x01\x01\x12&\n" +
	"\fpackage_hash\x18\x03 \x01(\tH\x02R\vpackageHash\x88\x01\x01\x12=\n" +
	"\bmanifest\x18\x04 \x01(\v2\x1c.massive.plan.v0.ArtifactRefH\x03R\bmanifest\x88\x01\x01\x12H\n" +
	"\x0esource_archive\x18\x05 \x01(\v2\x1c.massive.plan.v0.ArtifactRefH\x04R\rsourceArchive\x88\x01\x01B\r\n" +
	"\v_package_idB\v\n" +
	"\t_languageB\x0f\n" +
	"\r_package_hashB\v\n" +
	"\t_manifestB\x11\n" +
	"\x0f_source_archive\"\xac\x02\n" +
	"\x17MaterializedEnvironment\x12\x1c\n" +
	"\aenv_ref\x18\x01 \x01(\tH\x00R\x06envRef\x88\x01\x01\x12 \n" +
	"\tspec_hash\x18\x02 \x01(\tH\x01R\bspecHash\x88\x01\x01\x12\x17\n" +
	"\x04kind\x18\x03 \x01(\tH\x02R\x04kind\x88\x01\x01\x127\n" +
	"\x05local\x18\x04 \x01(\v2\x1c.massive.plan.v0.ArtifactRefH\x03R\x05local\x88\x01\x01\x12D\n" +
	"\tcontainer\x18\x05 \x01(\v2!.massive.plan.v0.ContainerRuntimeH\x04R\tcontainer\x88\x01\x01B\n" +
	"\n" +
	"\b_env_refB\f\n" +
	"\n" +
	"_spec_hashB\a\n" +
	"\x05_kindB\b\n" +
	"\x06_localB\f\n" +
	"\n" +
	"_container\"\x8e\x01\n" +
	"\x10ContainerRuntime\x12\x19\n" +
	"\x05image\x18\x01 \x01(\tH\x00R\x05image\x88\x01\x01\x12D\n" +
	"\fsource_fetch\x18\x02 \x01(\v2\x1c.massive.plan.v0.ArtifactRefH\x01R\vsourceFetch\x88\x01\x01B\b\n" +
	"\x06_imageB\x0f\n" +
	"\r_source_fetch\"\xe7\x02\n" +
	"\x11ExecutionContract\x12&\n" +
	"\fcontract_ref\x18\x01 \x01(\tH\x00R\vcontractRef\x88\x01\x01\x12,\n" +
	"\x0fenvironment_ref\x18\x02 \x01(\tH\x01R\x0eenvironmentRef\x88\x01\x01\x12H\n" +
	"\tresources\x18\x03 \x01(\v2%.massive.plan.v0.ResourceRequirementsH\x02R\tresources\x88\x01\x01\x124\n" +
	"\asecrets\x18\x04 \x03(\v2\x1a.massive.plan.v0.SecretRefR\asecrets\x12=\n" +
	"\anetwork\x18\x05 \x01(\v2\x1e.massive.plan.v0.NetworkPolicyH\x03R\anetwork\x88\x01\x01B\x0f\n" +
	"\r_contract_refB\x12\n" +
	"\x10_environment_refB\f\n" +
	"\n" +
	"_resourcesB\n" +
	"\n" +
	"\b_network\"]\n" +
	"\x14ResourceRequirements\x12\x15\n" +
	"\x03cpu\x18\x01 \x01(\tH\x00R\x03cpu\x88\x01\x01\x12\x1b\n" +
	"\x06memory\x18\x02 \x01(\tH\x01R\x06memory\x88\x01\x01B\x06\n" +
	"\x04_cpuB\t\n" +
	"\a_memory\"L\n" +
	"\tSecretRef\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x15\n" +
	"\x03ref\x18\x02 \x01(\tH\x01R\x03ref\x88\x01\x01B\a\n" +
	"\x05_nameB\x06\n" +
	"\x04_ref\"M\n" +
	"\rNetworkPolicy\x12\x1b\n" +
	"\x06egress\x18\x01 \x01(\tH\x00R\x06egress\x88\x01\x01\x12\x14\n" +
	"\x05hosts\x18\x02 \x03(\tR\x05hostsB\t\n" +
	"\a_egress\"\xc4\x01\n" +
	"\n" +
	"TargetPlan\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tH\x00R\x04kind\x88\x01\x01\x12$\n" +
	"\vtarget_hash\x18\x02 \x01(\tH\x01R\n" +
	"targetHash\x88\x01\x01\x12J\n" +
	"\x0fbundle_manifest\x18\x03 \x01(\v2\x1c.massive.plan.v0.ArtifactRefH\x02R\x0ebundleManifest\x88\x01\x01B\a\n" +
	"\x05_kindB\x0e\n" +
	"\f_target_hashB\x12\n" +
	"\x10_bundle_manifest\"\xd9\x01\n" +
	"\x12CompilerProvenance\x12(\n" +
	"\rcompiler_name\x18\x01 \x01(\tH\x00R\fcompilerName\x88\x01\x01\x12.\n" +
	"\x10compiler_version\x18\x02 \x01(\tH\x01R\x0fcompilerVersion\x88\x01\x01\x12-\n" +
	"\x10source_spec_hash\x18\x03 \x01(\tH\x02R\x0esourceSpecHash\x88\x01\x01B\x10\n" +
	"\x0e_compiler_nameB\x13\n" +
	"\x11_compiler_versionB\x13\n" +
	"\x11_source_spec_hashB=Z;github.com/Sly1029/massive/conformance/schema/planpb;planpbb\x06proto3"

var (
	file_workflow_plan_proto_rawDescOnce sync.Once
	file_workflow_plan_proto_rawDescData []byte
)

func file_workflow_plan_proto_rawDescGZIP() []byte {
	file_workflow_plan_proto_rawDescOnce.Do(func() {
		file_workflow_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_plan_proto_rawDesc), len(file_workflow_plan_proto_rawDesc)))
	})
	return file_workflow_plan_proto_rawDescData
}

var file_workflow_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_workflow_plan_proto_goTypes = []any{
	(*ArtifactRef)(nil),             // 0: massive.plan.v0.ArtifactRef
	(*WorkflowPlan)(nil),            // 1: massive.plan.v0.WorkflowPlan
	(*GraphIR)(nil),                 // 2: massive.plan.v0.GraphIR
	(*GraphNode)(nil),               // 3: massive.plan.v0.GraphNode
	(*GraphEdge)(nil),               // 4: massive.plan.v0.GraphEdge
	(*SchemaEntry)(nil),             // 5: massive.plan.v0.SchemaEntry
	(*SymbolEntry)(nil),             // 6: massive.plan.v0.SymbolEntry
	(*SourcePackageRef)(nil),        // 7: massive.plan.v0.SourcePackageRef
	(*MaterializedEnvironment)(nil), // 8: massive.plan.v0.MaterializedEnvironment
	(*ContainerRuntime)(nil),        // 9: massive.plan.v0.ContainerRuntime
	(*ExecutionContract)(nil),       // 10: massive.plan.v0.ExecutionContract
	(*ResourceRequirements)(nil),    // 11: massive.plan.v0.ResourceRequirements
	(*SecretRef)(nil),               // 12: massive.plan.v0.SecretRef
	(*NetworkPolicy)(nil),           // 13: massive.plan.v0.NetworkPolicy
	(*TargetPlan)(nil),              // 14: massive.plan.v0.TargetPlan
	(*CompilerProvenance)(nil),      // 15: massive.plan.v0.CompilerProvenance
}
var file_workflow_plan_proto_depIdxs = []int32{
	2,  // 0: massive.plan.v0.WorkflowPlan.graph:type_name -> massive.plan.v0.GraphIR
	5,  // 1: massive.plan.v0.WorkflowPlan.schemas:type_name -> massive.plan.v0.SchemaEntry
	6,  // 2: massive.plan.v0.WorkflowPlan.symbols:type_name -> massive.plan.v0.SymbolEntry
	7,  // 3: massive.plan.v0.WorkflowPlan.source_packages:type_name -> massive.plan.v0.SourcePackageRef
	8,  // 4: massive.plan.v0.WorkflowPlan.environments:type_name -> massive.plan.v0.MaterializedEnvironment
	10, // 5: massive.plan.v0.WorkflowPlan.contracts:type_name -> massive.plan.v0.ExecutionContract
	14, // 6: massive.plan.v0.WorkflowPlan.targets:type_name -> massive.plan.v0.TargetPlan
	0,  // 7: massive.plan.v0.WorkflowPlan.datastore_manifests:type_name -> massive.plan.v0.ArtifactRef
	15, // 8: massive.plan.v0.WorkflowPlan.provenance:type_name -> massive.plan.v0.CompilerProvenance
	3,  // 9: massive.plan.v0.GraphIR.nodes:type_name -> massive.plan.v0.GraphNode
	4,  // 10: massive.plan.v0.GraphIR.edges:type_name -> massive.plan.v0.GraphEdge
	0,  // 11: massive.plan.v0.SourcePackageRef.manifest:type_name -> massive.plan.v0.ArtifactRef
	0,  // 12: massive.plan.v0.SourcePackageRef.source_archive:type_name -> massive.plan.v0.ArtifactRef
	0,  // 13: massive.plan.v0.MaterializedEnvironment.local:type_name -> massive.plan.v0.ArtifactRef
	9,  // 14: massive.plan.v0.MaterializedEnvironment.container:type_name -> massive.plan.v0.ContainerRuntime
	0,  // 15: massive.plan.v0.ContainerRuntime.source_fetch:type_name -> massive.plan.v0.ArtifactRef
	11, // 16: massive.plan.v0.ExecutionContract.resources:type_name -> massive.plan.v0.ResourceRequirements
	12, // 17: massive.plan.v0.ExecutionContract.secrets:type_name -> massive.plan.v0.SecretRef
	13, // 18: massive.plan.v0.ExecutionContract.network:type_name -> massive.plan.v0.NetworkPolicy
	0,  // 19: massive.plan.v0.TargetPlan.bundle_manifest:type_name -> massive.plan.v0.ArtifactRef
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_workflow_plan_proto_init() }
func file_workflow_plan_proto_init() {
	if File_workflow_plan_proto != nil {
		return
	}
	file_workflow_plan_proto_msgTypes[0].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[1].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[2].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[3].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[4].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[5].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[6].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[7].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[8].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[9].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[10].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[11].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[12].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[13].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[14].OneofWrappers = []any{}
	file_workflow_plan_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_plan_proto_rawDesc), len(file_workflow_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_plan_proto_goTypes,
		DependencyIndexes: file_workflow_plan_proto_depIdxs,
		MessageInfos:      file_workflow_plan_proto_msgTypes,
	}.Build()
	File_workflow_plan_proto = out.File
	file_workflow_plan_proto_goTypes = nil
	file_workflow_plan_proto_depIdxs = nil
}
