// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: step-invocation.proto

package runtimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Runner boundary owned by Massive rather than any language SDK. The v2 wire
// format is the canonical proto-JSON projection of this message, followed by
// canonical-json-v0 key ordering. All required scalars use explicit presence;
// the frozen JSON Schema applies value and conditional datastore constraints.
type StepInvocationDescriptor struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	Kind           *string                          `protobuf:"bytes,1,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	SchemaVersion  *uint32                          `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3,oneof" json:"schema_version,omitempty"`
	Encoding       *string                          `protobuf:"bytes,3,opt,name=encoding,proto3,oneof" json:"encoding,omitempty"`
	PlanHash       *string                          `protobuf:"bytes,4,opt,name=plan_hash,json=planHash,proto3,oneof" json:"plan_hash,omitempty"`
	ProjectKey     *string                          `protobuf:"bytes,5,opt,name=project_key,json=projectKey,proto3,oneof" json:"project_key,omitempty"`
	RunId          *string                          `protobuf:"bytes,6,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	NodeId         *string                          `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`
	Attempt        *uint32                          `protobuf:"varint,8,opt,name=attempt,proto3,oneof" json:"attempt,omitempty"`
	Scope          *ExecutionScope                  `protobuf:"bytes,9,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	Symbol         *StepSymbol                      `protobuf:"bytes,10,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	SourcePackage  *SourcePackage                   `protobuf:"bytes,11,opt,name=source_package,json=sourcePackage,proto3,oneof" json:"source_package,omitempty"`
	EnvironmentRef *string                          `protobuf:"bytes,12,opt,name=environment_ref,json=environmentRef,proto3,oneof" json:"environment_ref,omitempty"`
	Input          *DataArtifactRef                 `protobuf:"bytes,13,opt,name=input,proto3,oneof" json:"input,omitempty"`
	Output         *DataArtifactManifestDestination `protobuf:"bytes,14,opt,name=output,proto3,oneof" json:"output,omitempty"`
	ChannelReads   []*ChannelArtifactRef            `protobuf:"bytes,15,rep,name=channel_reads,json=channelReads,proto3" json:"channel_reads,omitempty"`
	ChannelWrites  []*ChannelArtifactDestination    `protobuf:"bytes,16,rep,name=channel_writes,json=channelWrites,proto3" json:"channel_writes,omitempty"`
	Datastore      *Datastore                       `protobuf:"bytes,17,opt,name=datastore,proto3,oneof" json:"datastore,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StepInvocationDescriptor) Reset() {
	*x = StepInvocationDescriptor{}
	mi := &file_step_invocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepInvocationDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepInvocationDescriptor) ProtoMessage() {}

func (x *StepInvocationDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepInvocationDescriptor.ProtoReflect.Descriptor instead.
func (*StepInvocationDescriptor) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{0}
}

func (x *StepInvocationDescriptor) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *StepInvocationDescriptor) GetSchemaVersion() uint32 {
	if x != nil && x.SchemaVersion != nil {
		return *x.SchemaVersion
	}
	return 0
}

func (x *StepInvocationDescriptor) GetEncoding() string {
	if x != nil && x.Encoding != nil {
		return *x.Encoding
	}
	return ""
}

func (x *StepInvocationDescriptor) GetPlanHash() string {
	if x != nil && x.PlanHash != nil {
		return *x.PlanHash
	}
	return ""
}

func (x *StepInvocationDescriptor) GetProjectKey() string {
	if x != nil && x.ProjectKey != nil {
		return *x.ProjectKey
	}
	return ""
}

func (x *StepInvocationDescriptor) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

func (x *StepInvocationDescriptor) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *StepInvocationDescriptor) GetAttempt() uint32 {
	if x != nil && x.Attempt != nil {
		return *x.Attempt
	}
	return 0
}

func (x *StepInvocationDescriptor) GetScope() *ExecutionScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *StepInvocationDescriptor) GetSymbol() *StepSymbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *StepInvocationDescriptor) GetSourcePackage() *SourcePackage {
	if x != nil {
		return x.SourcePackage
	}
	return nil
}

func (x *StepInvocationDescriptor) GetEnvironmentRef() string {
	if x != nil && x.EnvironmentRef != nil {
		return *x.EnvironmentRef
	}
	return ""
}

func (x *StepInvocationDescriptor) GetInput() *DataArtifactRef {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *StepInvocationDescriptor) GetOutput() *DataArtifactManifestDestination {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *StepInvocationDescriptor) GetChannelReads() []*ChannelArtifactRef {
	if x != nil {
		return x.ChannelReads
	}
	return nil
}

func (x *StepInvocationDescriptor) GetChannelWrites() []*ChannelArtifactDestination {
	if x != nil {
		return x.ChannelWrites
	}
	return nil
}

func (x *StepInvocationDescriptor) GetDatastore() *Datastore {
	if x != nil {
		return x.Datastore
	}
	return nil
}

type ExecutionScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*MapItemScopeFrame   `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionScope) Reset() {
	*x = ExecutionScope{}
	mi := &file_step_invocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionScope) ProtoMessage() {}

func (x *ExecutionScope) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionScope.ProtoReflect.Descriptor instead.
func (*ExecutionScope) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionScope) GetFrames() []*MapItemScopeFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

type MapItemScopeFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          *string                `protobuf:"bytes,1,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	MapId         *string                `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3,oneof" json:"map_id,omitempty"`
	Index         *uint32                `protobuf:"varint,3,opt,name=index,proto3,oneof" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapItemScopeFrame) Reset() {
	*x = MapItemScopeFrame{}
	mi := &file_step_invocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapItemScopeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapItemScopeFrame) ProtoMessage() {}

func (x *MapItemScopeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapItemScopeFrame.ProtoReflect.Descriptor instead.
func (*MapItemScopeFrame) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{2}
}

func (x *MapItemScopeFrame) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *MapItemScopeFrame) GetMapId() string {
	if x != nil && x.MapId != nil {
		return *x.MapId
	}
	return ""
}

func (x *MapItemScopeFrame) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type StepSymbol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     *string                `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3,oneof" json:"package_id,omitempty"`
	Language      *string                `protobuf:"bytes,2,opt,name=language,proto3,oneof" json:"language,omitempty"`
	Module        *string                `protobuf:"bytes,3,opt,name=module,proto3,oneof" json:"module,omitempty"`
	Export        *string                `protobuf:"bytes,4,opt,name=export,proto3,oneof" json:"export,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepSymbol) Reset() {
	*x = StepSymbol{}
	mi := &file_step_invocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepSymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepSymbol) ProtoMessage() {}

func (x *StepSymbol) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepSymbol.ProtoReflect.Descriptor instead.
func (*StepSymbol) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{3}
}

func (x *StepSymbol) GetPackageId() string {
	if x != nil && x.PackageId != nil {
		return *x.PackageId
	}
	return ""
}

func (x *StepSymbol) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *StepSymbol) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

func (x *StepSymbol) GetExport() string {
	if x != nil && x.Export != nil {
		return *x.Export
	}
	return ""
}

type SourcePackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     *string                `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3,oneof" json:"package_id,omitempty"`
	Language      *string                `protobuf:"bytes,2,opt,name=language,proto3,oneof" json:"language,omitempty"`
	PackageHash   *string                `protobuf:"bytes,3,opt,name=package_hash,json=packageHash,proto3,oneof" json:"package_hash,omitempty"`
	SourceArchive *ArtifactRef           `protobuf:"bytes,4,opt,name=source_archive,json=sourceArchive,proto3,oneof" json:"source_archive,omitempty"`
	Manifest      *ArtifactRef           `protobuf:"bytes,5,opt,name=manifest,proto3,oneof" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcePackage) Reset() {
	*x = SourcePackage{}
	mi := &file_step_invocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcePackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcePackage) ProtoMessage() {}

func (x *SourcePackage) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcePackage.ProtoReflect.Descriptor instead.
func (*SourcePackage) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{4}
}

func (x *SourcePackage) GetPackageId() string {
	if x != nil && x.PackageId != nil {
		return *x.PackageId
	}
	return ""
}

func (x *SourcePackage) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *SourcePackage) GetPackageHash() string {
	if x != nil && x.PackageHash != nil {
		return *x.PackageHash
	}
	return ""
}

func (x *SourcePackage) GetSourceArchive() *ArtifactRef {
	if x != nil {
		return x.SourceArchive
	}
	return nil
}

func (x *SourcePackage) GetManifest() *ArtifactRef {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Hash          *string                `protobuf:"bytes,2,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
	ContentType   *string                `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_step_invocation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{5}
}

func (x *ArtifactRef) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ArtifactRef) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

func (x *ArtifactRef) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

type ArtifactDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key,proto3,oneof" json:"key,omitempty"`
	ContentType   *string                `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactDestination) Reset() {
	*x = ArtifactDestination{}
	mi := &file_step_invocation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactDestination) ProtoMessage() {}

func (x *ArtifactDestination) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactDestination.ProtoReflect.Descriptor instead.
func (*ArtifactDestination) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{6}
}

func (x *ArtifactDestination) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ArtifactDestination) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

type DataArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *ArtifactRef           `protobuf:"bytes,1,opt,name=artifact,proto3,oneof" json:"artifact,omitempty"`
	Schema        *string                `protobuf:"bytes,2,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataArtifactRef) Reset() {
	*x = DataArtifactRef{}
	mi := &file_step_invocation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataArtifactRef) ProtoMessage() {}

func (x *DataArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataArtifactRef.ProtoReflect.Descriptor instead.
func (*DataArtifactRef) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{7}
}

func (x *DataArtifactRef) GetArtifact() *ArtifactRef {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *DataArtifactRef) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return ""
}

type DataArtifactManifestDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestKey   *string                `protobuf:"bytes,1,opt,name=manifest_key,json=manifestKey,proto3,oneof" json:"manifest_key,omitempty"`
	Schema        *string                `protobuf:"bytes,2,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataArtifactManifestDestination) Reset() {
	*x = DataArtifactManifestDestination{}
	mi := &file_step_invocation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataArtifactManifestDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataArtifactManifestDestination) ProtoMessage() {}

func (x *DataArtifactManifestDestination) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataArtifactManifestDestination.ProtoReflect.Descriptor instead.
func (*DataArtifactManifestDestination) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{8}
}

func (x *DataArtifactManifestDestination) GetManifestKey() string {
	if x != nil && x.ManifestKey != nil {
		return *x.ManifestKey
	}
	return ""
}

func (x *DataArtifactManifestDestination) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return ""
}

type ChannelArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelName   *string                `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3,oneof" json:"channel_name,omitempty"`
	Artifact      *ArtifactRef           `protobuf:"bytes,2,opt,name=artifact,proto3,oneof" json:"artifact,omitempty"`
	Schema        *string                `protobuf:"bytes,3,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelArtifactRef) Reset() {
	*x = ChannelArtifactRef{}
	mi := &file_step_invocation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelArtifactRef) ProtoMessage() {}

func (x *ChannelArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelArtifactRef.ProtoReflect.Descriptor instead.
func (*ChannelArtifactRef) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelArtifactRef) GetChannelName() string {
	if x != nil && x.ChannelName != nil {
		return *x.ChannelName
	}
	return ""
}

func (x *ChannelArtifactRef) GetArtifact() *ArtifactRef {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *ChannelArtifactRef) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return ""
}

type ChannelArtifactDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelName   *string                `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3,oneof" json:"channel_name,omitempty"`
	Artifact      *ArtifactDestination   `protobuf:"bytes,2,opt,name=artifact,proto3,oneof" json:"artifact,omitempty"`
	Schema        *string                `protobuf:"bytes,3,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelArtifactDestination) Reset() {
	*x = ChannelArtifactDestination{}
	mi := &file_step_invocation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelArtifactDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelArtifactDestination) ProtoMessage() {}

func (x *ChannelArtifactDestination) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelArtifactDestination.ProtoReflect.Descriptor instead.
func (*ChannelArtifactDestination) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{10}
}

func (x *ChannelArtifactDestination) GetChannelName() string {
	if x != nil && x.ChannelName != nil {
		return *x.ChannelName
	}
	return ""
}

func (x *ChannelArtifactDestination) GetArtifact() *ArtifactDestination {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *ChannelArtifactDestination) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return ""
}

// The v2 JSON projection predates this proto and uses a flat tagged union.
// kind selects the valid field set; the JSON Schema rejects mixed variants.
type Datastore struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           *string                `protobuf:"bytes,1,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	Path           *string                `protobuf:"bytes,2,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Bucket         *string                `protobuf:"bytes,3,opt,name=bucket,proto3,oneof" json:"bucket,omitempty"`
	Region         *string                `protobuf:"bytes,4,opt,name=region,proto3,oneof" json:"region,omitempty"`
	Prefix         *string                `protobuf:"bytes,5,opt,name=prefix,proto3,oneof" json:"prefix,omitempty"`
	Endpoint       *string                `protobuf:"bytes,6,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	ForcePathStyle *bool                  `protobuf:"varint,7,opt,name=force_path_style,json=forcePathStyle,proto3,oneof" json:"force_path_style,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Datastore) Reset() {
	*x = Datastore{}
	mi := &file_step_invocation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Datastore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datastore) ProtoMessage() {}

func (x *Datastore) ProtoReflect() protoreflect.Message {
	mi := &file_step_invocation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datastore.ProtoReflect.Descriptor instead.
func (*Datastore) Descriptor() ([]byte, []int) {
	return file_step_invocation_proto_rawDescGZIP(), []int{11}
}

func (x *Datastore) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *Datastore) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *Datastore) GetBucket() string {
	if x != nil && x.Bucket != nil {
		return *x.Bucket
	}
	return ""
}

func (x *Datastore) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *Datastore) GetPrefix() string {
	if x != nil && x.Prefix != nil {
		return *x.Prefix
	}
	return ""
}

func (x *Datastore) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *Datastore) GetForcePathStyle() bool {
	if x != nil && x.ForcePathStyle != nil {
		return *x.ForcePathStyle
	}
	return false
}

var File_step_invocation_proto protoreflect.FileDescriptor

const file_step_invocation_proto_rawDesc = "" +
	"\n" +
	"\x15step-invocation.proto\x12\x12massive.runtime.v2\"\xdb\b\n" +
	"\x18StepInvocationDescriptor\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tH\x00R\x04kind\x88\x01\x01\x12*\n" +
	"\x0eschema_version\x18\x02 \x01(\rH\x01R\rschemaVersion\x88\x01\x01\x12\x1f\n" +
	"\bencoding\x18\x03 \x01(\tH\x02R\bencoding\x88\x01\x01\x12 \n" +
	"\tplan_hash\x18\x04 \x01(\tH\x03R\bplanHash\x88\x01\x01\x12$\n" +
	"\vproject_key\x18\x05 \x01(\tH\x04R\n" +
	"projectKey\x88\x01\x01\x12\x1a\n" +
	"\x06run_id\x18\x06 \x01(\tH\x05R\x05runId\x88\x01\x01\x12\x1c\n" +
	"\anode_id\x18\a \x01(\tH\x06R\x06nodeId\x88\x01\x01\x12\x1d\n" +
	"\aattempt\x18\b \x01(\rH\aR\aattempt\x88\x01\x01\x12=\n" +
	"\x05scope\x18\t \x01(\v2\".massive.runtime.v2.ExecutionScopeH\bR\x05scope\x88\x01\x01\x12;\n" +
	"\x06symbol\x18\n" +
	" \x01(\v2\x1e.massive.runtime.v2.StepSymbolH\tR\x06symbol\x88\x01\x01\x12M\n" +
	"\x0esource_package\x18\v \x01(\v2!.massive.runtime.v2.SourcePackageH\n" +
	"R\rsourcePackage\x88\x01\x01\x12,\n" +
	"\x0fenvironment_ref\x18\f \x01(\tH\vR\x0eenvironmentRef\x88\x01\x01\x12>\n" +
	"\x05input\x18\r \x01(\v2#.massive.runtime.v2.DataArtifactRefH\fR\x05input\x88\x01\x01\x12P\n" +
	"\x06output\x18\x0e \x01(\v23.massive.runtime.v2.DataArtifactManifestDestinationH\rR\x06output\x88\x01\x01\x12K\n" +
	"\rchannel_reads\x18\x0f \x03(\v2&.massive.runtime.v2.ChannelArtifactRefR\fchannelReads\x12U\n" +
	"\x0echannel_writes\x18\x10 \x03(\v2..massive.runtime.v2.ChannelArtifactDestinationR\rchannelWrites\x12@\n" +
	"\tdatastore\x18\x11 \x01(\v2\x1d.massive.runtime.v2.DatastoreH\x0eR\tdatastore\x88\x01\x01B\a\n" +
	"\x05_kindB\x11\n" +
	"\x0f_schema_versionB\v\n" +
	"\t_encodingB\f\n" +
	"\n" +
	"_plan_hashB\x0e\n" +
	"\f_project_keyB\t\n" +
	"\a_run_idB\n" +
	"\n" +
	"\b_node_idB\n" +
	"\n" +
	"\b_attemptB\b\n" +
	"\x06_scopeB\t\n" +
	"\a_symbolB\x11\n" +
	"\x0f_source_packageB\x12\n" +
	"\x10_environment_refB\b\n" +
	"\x06_inputB\t\n" +
	"\a_outputB\f\n" +
	"\n" +
	"_datastore\"O\n" +
	"\x0eExecutionScope\x12=\n" +
	"\x06frames\x18\x01 \x03(\v2%.massive.runtime.v2.MapItemScopeFrameR\x06frames\"\x81\x01\n" +
	"\x11MapItemScopeFrame\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tH\x00R\x04kind\x88\x01\x01\x12\x1a\n" +
	"\x06map_id\x18\x02 \x01(\tH\x01R\x05mapId\x88\x01\x01\x12\x19\n" +
	"\x05index\x18\x03 \x01(\rH\x02R\x05index\x88\x01\x01B\a\n" +
	"\x05_kindB\t\n" +
	"\a_map_idB\b\n" +
	"\x06_index\"\xbd\x01\n" +
	"\n" +
	"StepSymbol\x12\"\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tH\x00R\tpackageId\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x02 \x01(\tH\x01R\blanguage\x88\x01\x01\x12\x1b\n" +
	"\x06module\x18\x03 \x01(\tH\x02R\x06module\x88\x01\x01\x12\x1b\n" +
	"\x06export\x18\x04 \x01(\tH\x03R\x06export\x88\x01\x01B\r\n" +
	"\v_package_idB\v\n" +
	"\t_languageB\t\n" +
	"\a_moduleB\t\n" +
	"\a_export\"\xd8\x02\n" +
	"\rSourcePackage\x12\"\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tH\x00R\tpackageId\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x02 \x01(\tH\x01R\blanguage\x88\x01\x01\x12&\n" +
	"\fpackage_hash\x18\x03 \x01(\tH\x02R\vpackageHash\x88\x01\x01\x12K\n" +
	"\x0esource_archive\x18\x04 \x01(\v2\x1f.massive.runtime.v2.ArtifactRefH\x03R\rsourceArchive\x88\x01\x01\x12@\n" +
	"\bmanifest\x18\x05 \x01(\v2\x1f.massive.runtime.v2.ArtifactRefH\x04R\bmanifest\x88\x01\x01B\r\n" +
	"\v_package_idB\v\n" +
	"\t_languageB\x0f\n" +
	"\r_package_hashB\x11\n" +
	"\x0f_source_archiveB\v\n" +
	"\t_manifest\"\x87\x01\n" +
	"\vArtifactRef\x12\x15\n" +
	"\x03key\x18\x01 \x01(\tH\x00R\x03key\x88\x01\x01\x12\x17\n" +
	"\x04hash\x18\x02 \x01(\tH\x01R\x04hash\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\x03 \x01(\tH\x02R\vcontentType\x88\x01\x01B\x06\n" +
	"\x04_keyB\a\n" +
	"\x05_hashB\x0f\n" +
	"\r_content_type\"m\n" +
	"\x13ArtifactDestination\x12\x15\n" +
	"\x03key\x18\x01 \x01(\tH\x00R\x03key\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\x02 \x01(\tH\x01R\vcontentType\x88\x01\x01B\x06\n" +
	"\x04_keyB\x0f\n" +
	"\r_content_type\"\x88\x01\n" +
	"\x0fDataArtifactRef\x12@\n" +
	"\bartifact\x18\x01 \x01(\v2\x1f.massive.runtime.v2.ArtifactRefH\x00R\bartifact\x88\x01\x01\x12\x1b\n" +
	"\x06schema\x18\x02 \x01(\tH\x01R\x06schema\x88\x01\x01B\v\n" +
	"\t_artifactB\t\n" +
	"\a_schema\"\x82\x01\n" +
	"\x1fDataArtifactManifestDestination\x12&\n" +
	"\fmanifest_key\x18\x01 \x01(\tH\x00R\vmanifestKey\x88\x01\x01\x12\x1b\n" +
	"\x06schema\x18\x02 \x01(\tH\x01R\x06schema\x88\x01\x01B\x0f\n" +
	"\r_manifest_keyB\t\n" +
	"\a_schema\"\xc4\x01\n" +
	"\x12ChannelArtifactRef\x12&\n" +
	"\fchannel_name\x18\x01 \x01(\tH\x00R\vchannelName\x88\x01\x01\x12@\n" +
	"\bartifact\x18\x02 \x01(\v2\x1f.massive.runtime.v2.ArtifactRefH\x01R\bartifact\x88\x01\x01\x12\x1b\n" +
	"\x06schema\x18\x03 \x01(\tH\x02R\x06schema\x88\x01\x01B\x0f\n" +
	"\r_channel_nameB\v\n" +
	"\t_artifactB\t\n" +
	"\a_schema\"\xd4\x01\n" +
	"\x1aChannelArtifactDestination\x12&\n" +
	"\fchannel_name\x18\x01 \x01(\tH\x00R\vchannelName\x88\x01\x01\x12H\n" +
	"\bartifact\x18\x02 \x01(\v2'.massive.runtime.v2.ArtifactDestinationH\x01R\bartifact\x88\x01\x01\x12\x1b\n" +
	"\x06schema\x18\x03 \x01(\tH\x02R\x06schema\x88\x01\x01B\x0f\n" +
	"\r_channel_nameB\v\n" +
	"\t_artifactB\t\n" +
	"\a_schema\"\xb9\x02\n" +
	"\tDatastore\x12\x17\n" +
	"\x04kind\x18\x01 \x01(\tH\x00R\x04kind\x88\x01\x01\x12\x17\n" +
	"\x04path\x18\x02 \x01(\tH\x01R\x04path\x88\x01\x01\x12\x1b\n" +
	"\x06bucket\x18\x03 \x01(\tH\x02R\x06bucket\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x04 \x01(\tH\x03R\x06region\x88\x01\x01\x12\x1b\n" +
	"\x06prefix\x18\x05 \x01(\tH\x04R\x06prefix\x88\x01\x01\x12\x1f\n" +
	"\bendpoint\x18\x06 \x01(\tH\x05R\bendpoint\x88\x01\x01\x12-\n" +
	"\x10force_path_style\x18\a \x01(\bH\x06R\x0eforcePathStyle\x88\x01\x01B\a\n" +
	"\x05_kindB\a\n" +
	"\x05_pathB\t\n" +
	"\a_bucketB\t\n" +
	"\a_regionB\t\n" +
	"\a_prefixB\v\n" +
	"\t_endpointB\x13\n" +
	"\x11_force_path_styleBCZAgithub.com/Sly1029/massive/conformance/schema/runtimepb;runtimepbb\x06proto3"

var (
	file_step_invocation_proto_rawDescOnce sync.Once
	file_step_invocation_proto_rawDescData []byte
)

func file_step_invocation_proto_rawDescGZIP() []byte {
	file_step_invocation_proto_rawDescOnce.Do(func() {
		file_step_invocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_step_invocation_proto_rawDesc), len(file_step_invocation_proto_rawDesc)))
	})
	return file_step_invocation_proto_rawDescData
}

var file_step_invocation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_step_invocation_proto_goTypes = []any{
	(*StepInvocationDescriptor)(nil),        // 0: massive.runtime.v2.StepInvocationDescriptor
	(*ExecutionScope)(nil),                  // 1: massive.runtime.v2.ExecutionScope
	(*MapItemScopeFrame)(nil),               // 2: massive.runtime.v2.MapItemScopeFrame
	(*StepSymbol)(nil),                      // 3: massive.runtime.v2.StepSymbol
	(*SourcePackage)(nil),                   // 4: massive.runtime.v2.SourcePackage
	(*ArtifactRef)(nil),                     // 5: massive.runtime.v2.ArtifactRef
	(*ArtifactDestination)(nil),             // 6: massive.runtime.v2.ArtifactDestination
	(*DataArtifactRef)(nil),                 // 7: massive.runtime.v2.DataArtifactRef
	(*DataArtifactManifestDestination)(nil), // 8: massive.runtime.v2.DataArtifactManifestDestination
	(*ChannelArtifactRef)(nil),              // 9: massive.runtime.v2.ChannelArtifactRef
	(*ChannelArtifactDestination)(nil),      // 10: massive.runtime.v2.ChannelArtifactDestination
	(*Datastore)(nil),                       // 11: massive.runtime.v2.Datastore
}
var file_step_invocation_proto_depIdxs = []int32{
	1,  // 0: massive.runtime.v2.StepInvocationDescriptor.scope:type_name -> massive.runtime.v2.ExecutionScope
	3,  // 1: massive.runtime.v2.StepInvocationDescriptor.symbol:type_name -> massive.runtime.v2.StepSymbol
	4,  // 2: massive.runtime.v2.StepInvocationDescriptor.source_package:type_name -> massive.runtime.v2.SourcePackage
	7,  // 3: massive.runtime.v2.StepInvocationDescriptor.input:type_name -> massive.runtime.v2.DataArtifactRef
	8,  // 4: massive.runtime.v2.StepInvocationDescriptor.output:type_name -> massive.runtime.v2.DataArtifactManifestDestination
	9,  // 5: massive.runtime.v2.StepInvocationDescriptor.channel_reads:type_name -> massive.runtime.v2.ChannelArtifactRef
	10, // 6: massive.runtime.v2.StepInvocationDescriptor.channel_writes:type_name -> massive.runtime.v2.ChannelArtifactDestination
	11, // 7: massive.runtime.v2.StepInvocationDescriptor.datastore:type_name -> massive.runtime.v2.Datastore
	2,  // 8: massive.runtime.v2.ExecutionScope.frames:type_name -> massive.runtime.v2.MapItemScopeFrame
	5,  // 9: massive.runtime.v2.SourcePackage.source_archive:type_name -> massive.runtime.v2.ArtifactRef
	5,  // 10: massive.runtime.v2.SourcePackage.manifest:type_name -> massive.runtime.v2.ArtifactRef
	5,  // 11: massive.runtime.v2.DataArtifactRef.artifact:type_name -> massive.runtime.v2.ArtifactRef
	5,  // 12: massive.runtime.v2.ChannelArtifactRef.artifact:type_name -> massive.runtime.v2.ArtifactRef
	6,  // 13: massive.runtime.v2.ChannelArtifactDestination.artifact:type_name -> massive.runtime.v2.ArtifactDestination
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_step_invocation_proto_init() }
func file_step_invocation_proto_init() {
	if File_step_invocation_proto != nil {
		return
	}
	file_step_invocation_proto_msgTypes[0].OneofWrappers = []any{}
	file_step_invocation_proto_msgTypes[2].OneofWrappers = []any{}
	file_step_invocation_proto_msgTypes[3].OneofWrappers = []any{}
	file_step_invocation_proto_msgTypes[4].OneofWrappers = []any{}
	file_step_invocation_proto_msgTypes[5].OneofWrappers = []any{}
	file_step_invocation_proto_msgTypes[6].OneofWrappers = []any{}
	file_step_invocation_proto_msgTypes[7].OneofWrappers = []any{}
	file_step_invocation_proto_msgTypes[8].OneofWrappers = []any{}
	file_step_invocation_proto_msgTypes[9].OneofWrappers = []any{}
	file_step_invocation_proto_msgTypes[10].OneofWrappers = []any{}
	file_step_invocation_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_step_invocation_proto_rawDesc), len(file_step_invocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_step_invocation_proto_goTypes,
		DependencyIndexes: file_step_invocation_proto_depIdxs,
		MessageInfos:      file_step_invocation_proto_msgTypes,
	}.Build()
	File_step_invocation_proto = out.File
	file_step_invocation_proto_goTypes = nil
	file_step_invocation_proto_depIdxs = nil
}
